### PR TITLE
fix: loaded session_types.json from api and assets

### LINKED ISSUE #1714: Loading of session_types json file
**Actual Behaviour**

Currently we are not loading the session_types json file from the assets folder and api.

**Expected Behaviour**

Loading the file along with other files.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

-

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/30

### PR DESCRIPTION
**Pull request by arp95**
Fixes #1714

Changes:

loaded session_types.json from api as well as the assets.

Screenshots for the change: 
-

@iamareebjamal @Shailesh351 @shreyasnbhat @rohanagarwal94 
please review.

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java [hunk 1]
```diff
@@ -727,7 +729,15 @@ public void handleJsonEvent(final JsonReadEvent jsonReadEvent) {
 
                     OpenEventApp.postEventOnUIThread(new MicrolocationDownloadEvent(true));
                     break;
-                } default:
+                }case ConstantStrings.SESSION_TYPES: {
+                    List<SessionType> sessionTypes = objectMapper.readValue(json, new TypeReference<List<SessionType>>() {});
```
Comment (Shailesh351) [inline android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: @arp95 Please look at https://github.com/iamareebjamal/open-event-android-sdk/pull/19/files#diff-101323bdb4e416731a603a3a109aba5bL55

Previous implementation has bug on parsing List<T>. Thanks.

Change it at other places also.

Comment (arp95) [reply android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: will do that. thanks for pointing out.
can you test the app? because it crashes after downloading the stuff and it is not because of this as per the logs. 
just confirm this. Thanks.

Comment (arp95) [reply android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: what does the "type" stand for over here?

Comment (Shailesh351) [reply android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: @arp95 it is Model class. If json file is event then type should be `Event.class`. Same at other places

File: apk-generator/v2/app/generator/generator.py [hunk 2]
```diff
@@ -221,6 +221,7 @@ def download_event_data(self):
         self.save_file_in_temp_assets('speakers')
         self.save_file_in_temp_assets('sponsors')
         self.save_file_in_temp_assets('tracks')
+	self.save_file_in_temp_assets('session_types')
```
Comment (iamareebjamal) [inline apk-generator/v2/app/generator/generator.py]: Please always test the generator after modification. This is indentation error

File: android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java [hunk 3]
```diff
@@ -265,6 +266,24 @@ private void saveSessionsInRealm(final List<Session> sessions) {
...
+
+                    if(stored != null) {
+                        session.setSessionType(stored);
+                    } else {
+                        //setting intermediate information
+                        if(sessionType.getName() == null) {
+                            sessionType.setName("");
+                        } else {
+                            sessionType.setName(sessionType.getName());
+                        }
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java]: Is this block needed? We should make null safe views instead, where we check that the name is null or not. And can an event have null session type name?

**Review by iamareebjamal — CHANGES_REQUESTED** [review]
Also, please increase the download counter and add appropriate message for session type in DownloadCompleteHandler and in static JSON loader in MainActivity

File: apk-generator/v2/app/generator/generator.py (hunk 2 above)
Comment (arp95) [reply apk-generator/v2/app/generator/generator.py]: checking it.

File: android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java (hunk 3 above)
Comment (arp95) [reply android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java]: looking into it.

**Comment by arp95** [comment]
@iamareebjamal @Shailesh351 @shreyasnbhat @rohanagarwal94 
please review.

**Comment by arp95** [comment]
Guys there is a crash, however download is happening properly. Can anyone figure out from the logs, couldnt find such.
Is it working fine for you?

**Comment by Shailesh351** [comment]
@arp95 https://www.codacy.com/app/mb/open-event-android/pullRequest?prid=736751 
Indentation problem.

**Comment by arp95** [comment]
@Shailesh351 
can you send the pr for that generator.py if possible?
rest is fine right?

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java [hunk 4]
```diff
@@ -708,26 +709,32 @@ public void handleJsonEvent(final JsonReadEvent jsonReadEvent) {
...
                     break;
                 } case ConstantStrings.MICROLOCATIONS: {
-                    List<Microlocation> microlocations = objectMapper.readValue(json, new TypeReference<List<Microlocation>>() {});
+                    List<Microlocation> microlocations = objectMapper.readValue(json, objectMapper.getTypeFactory().constructCollectionType(List.class, Microlocation.class));
 
                     realmRepo.saveLocations(microlocations).subscribe();
 
                     OpenEventApp.postEventOnUIThread(new MicrolocationDownloadEvent(true));
                     break;
+                }case ConstantStrings.SESSION_TYPES: {
```
Comment (Shailesh351) [inline android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: break statement missing

Comment (arp95) [reply android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: over here the indentation of generator.py shows some problem however codacy runs successfully.
on my private account link it is also fine: https://github.com/arp95/open-event-android/blob/development/apk-generator/v2/app/generator/generator.py
then what is the problem, is it the editor i am using?
The app seems to run fine now.

File: apk-generator/v2/app/generator/generator.py (hunk 2 above)
Comment (Shailesh351) [reply apk-generator/v2/app/generator/generator.py]: @arp95 here endpoint is 'sessions/types'.
https://eventyay.com/api/v1/events/6/sessions/types
http://open-event-dev.herokuapp.com/api/v1/#!/sessions/get_session_type_list

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java (hunk 4 above)
Comment (Shailesh351) [reply android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: indentation is correct now just change endpoint to 'sessions/types'
Also add sample session_types file in assets folder.

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: Add a space after `}` too

**Comment by arp95** [comment]
The app is working fine now.
Squashing the commits and sending the pr.

File: android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java [hunk 5]
```diff
@@ -468,6 +469,29 @@ public Completable saveLocations(final List<Microlocation> locations) {
...
+    }
+
+    public Completable saveSessionTypes(final List<SessionType> sessionTypes) {
+        return Completable.fromAction(() -> {
+            saveSessionTypesInRealm(sessionTypes);
+            Timber.d("Saved Session Types");
+        });
+    }
+
+    public RealmResults<SessionType> getSessionTypes() {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java:486]: Is there any use of this yet?

File: android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java [hunk 6]
```diff
@@ -468,6 +469,29 @@ public Completable saveLocations(final List<Microlocation> locations) {
         return realm.where(Microlocation.class).findAllSorted("name");
     }
 
+    //Session Types Section
+
+    private void saveSessionTypesInRealm(List<SessionType> sessionTypes) {
+        Realm realm = Realm.getDefaultInstance();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java]: Why not using the existing realm instance?

File: apk-generator/v2/app/generator/generator.py (hunk 2 above)
Comment (iamareebjamal) [inline apk-generator/v2/app/generator/generator.py]: Still indentation error. You have used a tab, whereas the file is indented using 4 spaces

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java [hunk 7]
```diff
@@ -708,26 +709,33 @@ public void handleJsonEvent(final JsonReadEvent jsonReadEvent) {
...
                 } case ConstantStrings.MICROLOCATIONS: {
-                    List<Microlocation> microlocations = objectMapper.readValue(json, new TypeReference<List<Microlocation>>() {});
+                    List<Microlocation> microlocations = objectMapper.readValue(json, objectMapper.getTypeFactory().constructCollectionType(List.class, Microlocation.class));
 
                     realmRepo.saveLocations(microlocations).subscribe();
 
                     OpenEventApp.postEventOnUIThread(new MicrolocationDownloadEvent(true));
                     break;
+                } case ConstantStrings.SESSION_TYPES: {
+                    List<SessionType> sessionTypes = objectMapper.readValue(json, objectMapper.getTypeFactory().constructCollectionType(List.class, SessionType.class));
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java:733]: Also increase the count here

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: apk-generator/v2/app/generator/generator.py [hunk 8]
```diff
@@ -221,6 +221,7 @@ def download_event_data(self):
         self.save_file_in_temp_assets('speakers')
         self.save_file_in_temp_assets('sponsors')
         self.save_file_in_temp_assets('tracks')
+        self.save_file_in_temp_assets('sessions/types')
         logger.info('Download complete')
```
Comment (arp95) [inline apk-generator/v2/app/generator/generator.py:225]: @iamareebjamal there is no indentation error. i know it is showing wrong here but i dont know the reason for it.
i think its fine now.

File: android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java (hunk 5 above)
Comment (arp95) [reply android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java:486]: for this pr no. i am adding it for future reference.
or should i remove it then?

File: android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java (hunk 6 above)
Comment (arp95) [reply android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java]: ok using that.

File: apk-generator/v2/app/generator/generator.py (hunk 8 above)
Comment (iamareebjamal) [reply apk-generator/v2/app/generator/generator.py:225]: I was looking at older commit. Sorry

File: android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java (hunk 5 above)
Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java:486]: No, let it be, was just confirming

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java (hunk 7 above)
Comment (arp95) [reply android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java:733]: what count? 
didnt get you.

**Comment by arp95** [comment]
@iamareebjamal @Shailesh351 @shreyasnbhat @rohanagarwal94 
please review now.

**Comment by arp95** [comment]
Guys please review.

**Review by Shailesh351 — APPROVED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java (hunk 7 above)
Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java:733]: There should be a count of JSON files to be read

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

**Comment by arp95** [comment]
@iamareebjamal 
are you saying adding this code to MainActivity.java as we did in the event processor file?

counterRequests = 7;
OpenEventApp.postEventOnUIThread(new CounterEvent(counterRequests));

and then simply decrement the count on each download?

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java (hunk 7 above)
Comment (Shailesh351) [reply android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java:733]: Yes here https://github.com/arp95/open-event-android/blob/72623f470e8c2882e4578c30a12b672eb8eeb1f4/android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java#L783

**Comment by arp95** [comment]
got it.

**Comment by iamareebjamal** [comment]
@arp95 No need to add, there should be a CounterEvent already posted there. Let me check

**Comment by iamareebjamal** [comment]
@arp95 In `downloadFromAssets`

```Java
OpenEventApp.postEventOnUIThread(new CounterEvent(6)); // Bump if increased
```

Increase to 7

**Comment by arp95** [comment]
@iamareebjamal 
done.

**Review by iamareebjamal — APPROVED** [review]

**Comment by arp95** [comment]
@mariobehling @the-dagger 
please review and merge.
