### PR TITLE
fix : Shadow between Toolbar and TabLayout

### LINKED ISSUE #1886: Shadow between Toolbar and TabLayout
**Actual Behaviour**

Shadow is appearing between Toolbar and TabLayout. It was fixed before(https://github.com/fossasia/open-event-android/issues/1582) but some how issue is appearing again.

Also settings Activity don't have actionbar elevation.

**Expected Behaviour**

Shadow should not be there. Add elevation in SettingsActivity actionbar

**Steps to reproduce it**

- Go to schedule fragment 
- Now switch to settings activity using navigation drawer
- Go back.

**Screenshots of the issue**

appbar-shadow

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

[Milestone 15](https://github.com/fossasia/open-event-android/milestone/38)

### PR DESCRIPTION
**Pull request by Shailesh351**
Fixes #1886

Changes:
- Fix Shadow between Toolbar and TabLayout
- Add elevation in Settings Activity actionbar
- Use dp instead of Px while setting elevation

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java [hunk 1]
```diff
@@ -495,6 +495,12 @@ private void replaceFragment(Fragment fragment, int title) {
             TAG = FRAGMENT_TAG_HOME;
         }
 
+        if (currentMenuItemId != R.id.nav_schedule) {
+            addShadowToAppBar(true);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: `addShadowToAppBar(currentMenuItemId != R.id.nav_schedule)`

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/SettingsActivity.java [hunk 2]
```diff
@@ -162,6 +163,9 @@ private void setToolbar() {
         setSupportActionBar((Toolbar) findViewById(R.id.setting_toolbar));
         getSupportActionBar().setDisplayOptions(ActionBar.DISPLAY_SHOW_HOME |
                 ActionBar.DISPLAY_HOME_AS_UP | ActionBar.DISPLAY_SHOW_TITLE);
+
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP)
+            getSupportActionBar().setElevation(12);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SettingsActivity.java]: This should be converted to dp to appear normal on each device

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

**Review by iamareebjamal — APPROVED** [review]
