### PR TITLE
fix : unnecessary elements in shared text have disappeared

### LINKED ISSUE #1971: Unnecessary elements showing up in shared text
**Actual Behaviour**

Unnecessary elements are showing up while sharing the session details.

**Expected Behaviour**

Relevant Details must show up while sharing details.

**Steps to reproduce it**

We parse the JSON elements correctly and align the details correctly.

**Screenshots of the issue**
screenshot_20171101-022526
screenshot_20171101-022536

**Would you like to work on the issue?**
Yes, I will work on this issue

### PR DESCRIPTION
**Pull request by dreadpool2**
Fixes #1971 

Changes: The Description part has been changed to a shorter abstract version of it and the Speakers names have been filtered out.

Screenshots for the change: 
screenshot_20180119-041703

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java [hunk 1]
```diff
@@ -358,16 +358,20 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 return true;
 
             case R.id.action_share:
+                String speakers = "";
+                for(int i = 0; i < session.getSpeakers().size(); i++){
+                    speakers +=  ((i == 0)?(""):(", ")) + session.getSpeakers().get(i).getName();
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: We should use ```StringBuilder``` here for concatenation since it is the recommended way in case of a loop. 
@iamareebjamal What do you think ?

**Review by dr0pdb — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java (hunk 1 above)
Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: Yes true

**Comment by dreadpool2** [comment]
@iamareebjamal DId the changes. Please review

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java [hunk 2]
```diff
@@ -358,16 +358,20 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 return true;
 
             case R.id.action_share:
+                StringBuilder speakers  = new StringBuilder("");
+                for(int i = 0; i < session.getSpeakers().size(); i++){
+                    speakers.append(((i == 0)?(""):(", ")) + session.getSpeakers().get(i).getName());
+                }
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: Where are you converting it back to the String ? After the for loop , convert it to a String using ```toString()```.

**Review by dr0pdb — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java (hunk 2 above)
Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: No need for `new StringBuilder("")`, `new StringBuilder()` will do

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: Rename `speakers` to `speakersNameBuilder`

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: Use for each loop instead

```
for (Speaker speaker: speakers) {
    // append
}

// remove the last character if builder is not empty
```

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java [hunk 3]
```diff
@@ -358,16 +358,22 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 return true;
 
             case R.id.action_share:
+                StringBuilder speakersNameBuilder  = new StringBuilder();
+                for(Speaker speaker : session.getSpeakers()){
+                    speakersNameBuilder.append(speaker.getName()+", ");
+                }
+                speakersNameBuilder.delete(speakers.length()-3,speakers.length()-1);
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: What is the use of this line ? 
The build fails because it can't find the ```speakers``` variable. Is it even working locally ?
Please always run the application after you make changes before pushing.

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java [hunk 4]
```diff
@@ -358,16 +358,22 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
                 String endTime = DateConverter.formatDateWithDefault(DateConverter.FORMAT_DATE_COMPLETE, session.getEndsAt());
-                String shareText = String.format("Session Track: %s \n" +
-                                "Title: %s \n" +
-                                "Start Time: %s \n" +
-                                "End Time: %s\n" +
-                                "Speakers: %s\n" +
-                                "Location: %s",
-                        trackName, title, startTime, endTime, StringUtils.join(speakers, ", "), location) +
-                        "\nDescription: " + Views.fromHtml(session.getLongAbstract());
+                String shareText = String.format(getResources().getString(R.string.session_track_details) + "%s \n" +
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: Add a space before %s like all other places

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

**Review by dr0pdb — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java (hunk 3 above)
Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: Also add appropriate spacing after for, +, - and comma

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java [hunk 5]
```diff
@@ -358,16 +358,22 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 return true;
 
             case R.id.action_share:
+                StringBuilder speakersNameBuilder  = new StringBuilder();
+                for(Speaker speaker : session.getSpeakers()){
+                    speakersNameBuilder.append(speaker.getName() + ", ");
+                }
+                speakersNameBuilder.delete(speakersNameBuilder.length() - 2, speakersNameBuilder.length() - 1);
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: I believe you're deleting the comma and the space after the last name of the speaker.
Please add a comment above this line ```deleting comma and space after last name``` or you can use a clearer way by using a boolean flag.

**Review by dr0pdb — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java (hunk 5 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: @srv-twry I added the comment 😅

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java [hunk 6]
```diff
@@ -358,16 +358,23 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 return true;
 
             case R.id.action_share:
+                StringBuilder speakersNameBuilder  = new StringBuilder();
+                for(Speaker speaker : session.getSpeakers()){
+                    speakersNameBuilder.append(speaker.getName() + ", ");
+                }
+                //deleting comma and space after last name
+                speakersNameBuilder.delete(speakersNameBuilder.length() - 2, speakersNameBuilder.length() - 1);
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: Even though i asked you to add that comment, now i feel it would be much better to use a boolean flag to add a comma and space i.e. don't add a comma and space when it's not required rather that adding it first and then deleting it.
Right now, the problem is, let's say the session.getSpeakers() returns an empty list. Then that for loop won't run at all but still you will try to delete something that isn't there and that would lead to error.

Can you use a boolean flag and only add comma and space when required ?

**Review by dr0pdb — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java (hunk 6 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: @srv-twry The list will always have a speaker right!

Comment (dr0pdb) [reply android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: I hope it has, but always good to be safe.

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: @srv-twry Well I could put a null check ?

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: @srv-twry Or I could implement your suggested method.

Comment (dr0pdb) [reply android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: The problem won't be resolved with a null check. Here is the problem:
1. You created a speakerNameBuilder object with empty string.
2. Now the session.getSpeakers() returns an empty list.
3. You try to delete the last two characters of the speakerNameBuilder, but wait !, it's empty. So you will get the error. It's like you're trying to delete something which isn't there.

Got it ?

The speakerNameBuilder won't be null but can be empty.

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: @srv-twry Yeah I did the changes 😅

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java [hunk 7]
```diff
@@ -358,16 +358,26 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 return true;
 
             case R.id.action_share:
+                StringBuilder speakersNameBuilder  = new StringBuilder();
+                for(Speaker speaker : session.getSpeakers()){
+                    if(speakersNameBuilder.toString().equals("")){
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: This(toString) is O(n) for each operation. So the whole ```for``` loop will be O(n^2) which is bad. Please use a boolean flag.

**Review by dr0pdb — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java (hunk 7 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: @srv-twry Using a boolean flag might involve another integer variable and `.size()` method too. Is it still advisable?

Comment (dr0pdb) [reply android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: It seems you haven't understood what i am suggesting. So here is the full implementation.

``` Java
boolean first = true;
for(Speaker speaker : session.getSpeakers()){
    if(!first) {
         speakersNameBuilder.append(", ");
    }
    speakersNameBuilder.append(speaker.getName());
    first = false;
}
```

Ignore indentation/formatting errors here.

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: @srv-twry Wow! That was neat! 😄

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java [hunk 8]
```diff
@@ -358,16 +358,26 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 return true;
 
             case R.id.action_share:
+                StringBuilder speakersNameBuilder  = new StringBuilder();
+                boolean firstSpeaker = true;
+                for(Speaker speaker : session.getSpeakers()){
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: Add a space after for and closing brace

File: android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java [hunk 9]
```diff
@@ -358,16 +358,26 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+                    if(!firstSpeaker) {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SessionDetailActivity.java]: Add space after if

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

**Comment by dreadpool2** [comment]
@iamareebjamal did the changes

**Review by iamareebjamal — APPROVED** [review]
