### PR TITLE
Fix custom tabs

### LINKED ISSUE #1885: Memory leak in SpeakersDetailActivity
**Actual Behaviour**

SpeakersDetailActivity has memory leak because of poor CustomTabService implementation. 

**Expected Behaviour**

Fix memory leak, remove redundant code and reuse Util method for CustomTabService.

**Screenshot of the issue**

screenshot-1503118892747
 

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

[Milestone 16](https://github.com/fossasia/open-event-android/milestone/39)

### PR DESCRIPTION
**Pull request by hardik124**
fix: Memory leak in custom tabs.  …
hardik124 committed 13 hours ago  
Uses default util method to implement custom tabs . Deletes speaker intent util.

Fixes #1885

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java [hunk 1]
```diff
@@ -91,11 +81,44 @@
...
+            case R.id.imageView_web:
+                url = speaker.getWebsite();
+                break;
+            default:
+                return;
+        }
+
+        if (!TextUtils.isEmpty(url)) {
+            if (customTabIntent == null)
+                customTabIntent = new CustomTabIntent(this);
```
Comment (Shailesh351) [inline android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java]: Hi @hardik124 Nice work :clap: 
Here No need to create new class `CustomTabIntent`. You can directly use Util method we have already created https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/utils/Utils.java#L110.

File: android/app/src/main/java/org/fossasia/openevent/utils/CustomTabIntent.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+        List<ResolveInfo> resolveInfos = context.getPackageManager().queryIntentServices(customTabIntent, 0);
+        customTabsSupported = !(resolveInfos == null || resolveInfos.isEmpty());
+
+        String URL = url;
+        if (!url.startsWith("http://") && !url.startsWith("https://")) {
+            URL = ("http://" + url);
+        }
+
+
+        if (customTabsSupported) {
```
Comment (Shailesh351) [inline android/app/src/main/java/org/fossasia/openevent/utils/CustomTabIntent.java]: I think CustomTabs have backword compabilities it will authomatically start intent to open URL if custom tabs is not supported.

Comment (Shailesh351) [reply android/app/src/main/java/org/fossasia/openevent/utils/CustomTabIntent.java]: I have tested it on API 18

File: android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java (hunk 1 above)
Comment (hardik124) [reply android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java]: Hi @Shailesh351 . Thanks. I didnt know about the Utils class. I will fix it ASAP.
In the original custom tab method(Utils). it crashes if URL is not valid . Should I use my code here to replace that ?

File: android/app/src/main/java/org/fossasia/openevent/utils/CustomTabIntent.java (hunk 2 above)
Comment (hardik124) [reply android/app/src/main/java/org/fossasia/openevent/utils/CustomTabIntent.java]: I will remove this part then. Thanks for telling me this.

File: android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java (hunk 1 above)
Comment (Shailesh351) [reply android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java]: Yes. Add check for URL is valid or not. For availability of CustomTabs i think it will be handled automatically if not available it will start intent.

**Comment by hardik124** [comment]
@Shailesh351, Please check now.

**Review by Shailesh351 — APPROVED** [review]
Looks good to me.
Please follow commit style https://github.com/fossasia/open-event-android/blob/development/docs/commitstyle.md

**Review by iamareebjamal — CHANGES_REQUESTED** [review]
Please squash the commits and follow the commit guideline posted above 😄

**Comment by hardik124** [comment]
@iamareebjamal @Shailesh351 I implemented the suggestions. Please check.

**Review by Shailesh351 — APPROVED** [review]

**Review by iamareebjamal — APPROVED** [review]
