### PR TITLE
fix : App crash on using bookmark widget

### LINKED ISSUE #1814: App crash on creating a bookmark widget
**Actual Behaviour**

The app crashes. The bookmark widget does not show the updated bookmarks from the app in the widget.

**Expected Behaviour**

The widget should work fine.

**Steps to reproduce it**
1. Add the bookmark widget in your phone.

**LogCat for the issue**

screenshot from 2017-07-13 20-22-41

**Would you like to work on the issue?**

Yes..

**Target Milestone to solve the issue**

[milestone 11](https://github.com/fossasia/open-event-android/milestone/33)

### PR DESCRIPTION
**Pull request by rohanagarwal94**
Fixes #1814
Realm access from incorrect thread.

@iamareebjamal @arp95 @Shailesh351 @shreyasnbhat @mahikaw please review.

### CODE REVIEW

**Review by arp95 — APPROVED** [review]
LGTM.

File: android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java [hunk 1]
```diff
@@ -336,6 +336,7 @@ public Session getSession(String title) {
     }
 
     public RealmResults<Session> getBookMarkedSessionsSync() {
+        Realm realm = Realm.getDefaultInstance();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java]: Close realm sessions whenever you create them

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java (hunk 1 above)
Comment (rohanagarwal94) [reply android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java]: Closing realm session does not result in updation of the bookmarks in the widget somehow.

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java]: Because the updates in the widget are dispatched by another mechanism and this is a synchronous query(non-updating). 

You should not rely on Realm to do it because leaking realm instance can lead to multiple databases being created. App data size can shoot up to 40 MB

**Comment by rohanagarwal94** [comment]
@iamareebjamal please review. Found this the only plausible solution. Could the constructor be anyway changed in the session?

**Comment by iamareebjamal** [comment]
You really don't need this. Just call `copyFromRealm` on the list of sessions in the widget service or provider

Secondly, this won't be needed because it is not the right way to do it, but still, you don't need to create this constructor, lombok will do that for you. Read lombok docs for further info in future.

**Comment by rohanagarwal94** [comment]
@iamareebjamal the problem of incorrect thread then persists as per your suggestion.

**Comment by iamareebjamal** [comment]
The problem is that you are expecting realm to update boomark widget, which is not correct thing to do. You can create a realm instance in the getBookmarkedSessionsSync method and close it before returning the list. It won't throw exception then

**Comment by rohanagarwal94** [comment]
@iamareebjamal I tried that too, it returned empty. I tried converting it to the list in the getBookmarkedSessionsSync and it worked out fine to some extent. The major problem in that case was the randomness in updation of bookmarks which @shreyasnbhat talked about while adding/deleting them. That is why as a last resort I had to turn to cloning.

**Comment by iamareebjamal** [comment]
This may be because at some places, the widget is being updated, and in other places it is not. Verify that each place is calling widget service to update

**Comment by rohanagarwal94** [comment]
@iamareebjamal please review.

**Comment by rohanagarwal94** [comment]
@shailesh351 @mahikaw @iamareebjamal @shreyasnbhat please review.

**Review by iamareebjamal — APPROVED** [review]

**Review by Shailesh351 — APPROVED** [review]

**Review by shreyasnbhat — APPROVED** [review]
