### PR TITLE
Location-wise upcoming session feature

### LINKED ISSUE #1350: show next session per room
**Actual Behaviour**

When I am attending a session in a room, I don't get information on what is coming up.

**Expected Behaviour**

It would be nice to have know about the next session in the current room (so I might stay) or even which ones are coming up (so I can go somewhere else).

**Steps to reproduce it**

Use the app when a session ends. (Yes, nothing happens.)

### PR DESCRIPTION
**Pull request by mahikaw**
Fixes #1350

Changes: 

- Added an "upcoming icon in the option's menu for each track. 

- On pressing, it displays the next session along with it's track drawable. In case of no upcoming sessions, simply displayed "No upcoming sessions"

Screenshots for the change: 

device-2017-07-07-185027

device-2017-07-07-185058

----
@the-dagger @niranjan94 @mananwason @shreyasnbhat @Shailesh351 @rohanagarwal94 @arp95 Please review. 
Also, I couldn't find a better icon for it, so any suggestions are welcome.

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 1]
```diff
@@ -44,14 +61,18 @@
     private final String FRAGMENT_TAG_LOCATION = "FTAGR";
 
     private GridLayoutManager gridLayoutManager;
+    Dialog upcomingDialogBox;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Use private please

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 2]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
         realmRepo.getSessionsByLocation(location)
                 .addChangeListener((sessions, orderedCollectionChangeSet) -> {
                     mSessions.clear();
+                    String upcoming_title="",track="",color;
                     mSessions.addAll(sessions);
+                    sorted_sessions=new ArrayList<Session>();
+                    sorted_sessions.clear();
+                    sorted_sessions.addAll(sessions.sort("startTime"));
+                    DateUtils convert=new DateUtils();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: DateUtils has static methods, no need of objects

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 3]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
         realmRepo.getSessionsByLocation(location)
                 .addChangeListener((sessions, orderedCollectionChangeSet) -> {
                     mSessions.clear();
+                    String upcoming_title="",track="",color;
                     mSessions.addAll(sessions);
+                    sorted_sessions=new ArrayList<Session>();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Why creating a new List every time? It can be done only once

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 4]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
         realmRepo.getSessionsByLocation(location)
                 .addChangeListener((sessions, orderedCollectionChangeSet) -> {
                     mSessions.clear();
+                    String upcoming_title="",track="",color;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Why not just querying and assigning? Is there a need to initialise it?

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 5]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
...
                     mSessions.addAll(sessions);
+                    sorted_sessions=new ArrayList<Session>();
+                    sorted_sessions.clear();
+                    sorted_sessions.addAll(sessions.sort("startTime"));
+                    DateUtils convert=new DateUtils();
+                    Date current=new Date(117,2,18,16,37);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Are these numbers relevant? If so, add comment why

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 6]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
...
+                    Date start=new Date();
+                    Date end=new Date();
+                    color = null;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Again, any reason this is assigned null?

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 7]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
...
+                    for (Session s:sorted_sessions){
+                        upcoming_title="";
+                        track="";
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Similarly as above

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java (hunk 3 above)
Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Also, please use camel case

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 8]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
...
                     mSessions.clear();
+                    String upcoming_title="",track="",color;
                     mSessions.addAll(sessions);
+                    sorted_sessions=new ArrayList<Session>();
+                    sorted_sessions.clear();
+                    sorted_sessions.addAll(sessions.sort("startTime"));
+                    DateUtils convert=new DateUtils();
+                    Date current=new Date(117,2,18,16,37);
+                    Date start=new Date();
+                    Date end=new Date();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Why creating new Dates when you can just query and assign

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 9]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
...
+                    for (Session s:sorted_sessions){
+                        upcoming_title="";
+                        track="";
+                        try {
+                            end=convert.getDate(s.getEndTime());
+                            start=convert.getDate(s.getStartTime());
+                        } catch (ParseException e) {
+                            e.printStackTrace();
+                        }
+                        if ((start.compareTo(current))>0){
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: There are date specific methods like `before` and `after`, compareTo is not recommended

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 10]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
...
+                            upcoming_title=s.getTitle();
+                            track=s.getTrack().toString();
+                            color=s.getTrack().getColor();
+                            break;
+                        }
+                    }
+                    if(upcoming_title!="") {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Use `TextUtils.isEmpty`

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 11]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
...
+                        int trackColor = Color.parseColor(color);
+                        upcomingSessionTitle.setText("Upcoming session: ");
+                        TextDrawable drawable = drawableBuilder.build(String.valueOf(track.charAt(0)), trackColor);
+                        trackImageIcon.setImageDrawable(drawable);
+                        trackImageIcon.setBackgroundColor(Color.TRANSPARENT);
+                        upcomingSessionText.setText(upcoming_title);
+
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Remove extra line

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 12]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
...
+                    }
+                    else
+
+                    {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Use Java style braces please

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 13]
```diff
@@ -241,4 +323,8 @@ public boolean onQueryTextChange(final String query) {
         }
         return filteredTracksList;
     }
+
+    public Activity getActivity() {
+        return this;
+    }
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: This seems unused

File: android/app/src/main/res/menu/menu_location_activity.xml [hunk 14]
```diff
@@ -9,12 +9,18 @@
             android:icon="@drawable/ic_search_white_24dp"
             android:title="@string/search"
             app:actionViewClass="android.support.v7.widget.SearchView"
-            app:showAsAction="ifRoom|collapseActionView" />
+            app:showAsAction="always" />
```
Comment (iamareebjamal) [inline android/app/src/main/res/menu/menu_location_activity.xml]: Use ifRoom

File: android/app/src/main/res/menu/menu_location_activity.xml [hunk 15]
```diff
@@ -9,12 +9,18 @@
...
 
         <item
             android:id="@+id/action_map_location"
             android:icon="@drawable/ic_map_white_24dp"
             android:title="@string/menu_map"
-            app:showAsAction="ifRoom" />
+            app:showAsAction="always" />
```
Comment (iamareebjamal) [inline android/app/src/main/res/menu/menu_location_activity.xml]: ifRoom

File: android/app/src/main/res/menu/menu_location_activity.xml [hunk 16]
```diff
@@ -9,12 +9,18 @@
...
+        <item
+                android:id="@+id/upcoming_sessions"
+                android:icon="@android:drawable/ic_menu_today"
+                android:title="@string/Upcoming"
+                app:showAsAction="always"
```
Comment (iamareebjamal) [inline android/app/src/main/res/menu/menu_location_activity.xml]: ifRoom

File: android/app/src/main/res/menu/menu_location_activity.xml [hunk 17]
```diff
@@ -9,12 +9,18 @@
...
 
         <item
             android:id="@+id/action_map_location"
             android:icon="@drawable/ic_map_white_24dp"
             android:title="@string/menu_map"
-            app:showAsAction="ifRoom" />
+            app:showAsAction="always" />
+        <item
+                android:id="@+id/upcoming_sessions"
+                android:icon="@android:drawable/ic_menu_today"
```
Comment (iamareebjamal) [inline android/app/src/main/res/menu/menu_location_activity.xml]: This will show icon from Gingerbread or Holo, use material icon vector drawable

**Review by iamareebjamal — CHANGES_REQUESTED** [review]
Also, create a new method and change stuff there

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 18]
```diff
@@ -44,14 +61,18 @@
     private final String FRAGMENT_TAG_LOCATION = "FTAGR";
 
     private GridLayoutManager gridLayoutManager;
+    Dialog upcomingDialogBox;
 
     private List<Session> mSessions = new ArrayList<>();
+    ArrayList<Session> sorted_sessions;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Use private

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 19]
```diff
@@ -61,11 +82,28 @@
...
+        trackImageIcon=(ImageView)upcomingDialogBox.findViewById(R.id.track_image_drawable);
+        upcomingSessionText = (TextView) upcomingDialogBox.findViewById(R.id.upcoming_session_textview);
+        upcomingSessionTitle=(TextView) upcomingDialogBox.findViewById(R.id.upcoming_Session_title);
+        dialogButton=(Button) upcomingDialogBox.findViewById(R.id.upcoming_button);
+        dialogButton.setOnClickListener(new View.OnClickListener() {
+            @Override
+            public void onClick(View view) {
+                upcomingDialogBox.dismiss();
+            }
+        });
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Transfer this in its own function

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 20]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
...
                     mSessions.clear();
+                    String upcoming_title="",track="",color;
                     mSessions.addAll(sessions);
+                    sorted_sessions=new ArrayList<Session>();
+                    sorted_sessions.clear();
+                    sorted_sessions.addAll(sessions.sort("startTime"));
+                    DateUtils convert=new DateUtils();
+                    Date current=new Date();
+                    Date start=new Date();
+                    Date end=new Date();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Why initialising start and end when you have to set it from the session?

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 21]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
...
+                    color = null;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Why assigning null to color?

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 22]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
...
+                        track="";
+                        try {
+                            end=convert.getDate(s.getEndTime());
+                            start=convert.getDate(s.getStartTime());
+                        } catch (ParseException e) {
+                            e.printStackTrace();
+                        }
+                        if ((start.compareTo(current))>0){
+                            upcoming_title=s.getTitle();
+                            track=s.getTrack().toString();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: This will convert the entire track object to string

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 23]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
...
+                        upcoming_title="";
+                        track="";
+                        try {
+                            end=convert.getDate(s.getEndTime());
+                            start=convert.getDate(s.getStartTime());
+                        } catch (ParseException e) {
+                            e.printStackTrace();
+                        }
+                        if ((start.compareTo(current))>0){
+                            upcoming_title=s.getTitle();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Use camel case

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 24]
```diff
@@ -101,7 +139,48 @@ protected void onResume() {
...
+                            track=s.getTrack().toString();
+                            color=s.getTrack().getColor();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Please write your code as if IDE would have formatted it. Spaces around `=`

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java (hunk 4 above)
Comment (mahikaw) [reply android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Yes. Android studio says to initialise them, else it gives an error.

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java (hunk 21 above)
Comment (mahikaw) [reply android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Because it gives an error if I don't initialise it.

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java (hunk 20 above)
Comment (mahikaw) [reply android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Gives an error otherwise.

**Comment by iamareebjamal** [comment]
@mahikaw Please ensure that the PR is ready before mentioning for review, or else set the title to [WIP]

**Comment by iamareebjamal** [comment]
@mahikaw Please see my outdated review, still many points are valid

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 25]
```diff
@@ -44,14 +52,18 @@
     private final String FRAGMENT_TAG_LOCATION = "FTAGR";
 
     private GridLayoutManager gridLayoutManager;
+    private Dialog upcomingDialogBox;
 
     private List<Session> mSessions = new ArrayList<>();
+    private ArrayList<Session> sorted_sessions;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Please use `List` and camelcase for variables

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 26]
```diff
@@ -101,14 +117,65 @@ protected void onResume() {
         realmRepo.getSessionsByLocation(location)
                 .addChangeListener((sessions, orderedCollectionChangeSet) -> {
                     mSessions.clear();
+                    String upcomingTitle="";
+                    String track="";
+                    String color;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: There's no need to declared and initialise variables, use `String track = session.getTrack.getTitle()`

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 27]
```diff
@@ -101,14 +117,65 @@ protected void onResume() {
...
                     mSessions.addAll(sessions);
+                    sorted_sessions=new ArrayList<Session>();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Use space between `=`

Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: There is no need to create new ArrayList each time

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 28]
```diff
@@ -101,14 +117,65 @@ protected void onResume() {
...
+                    sorted_sessions.clear();
+                    sorted_sessions.addAll(sessions.sort("startTime"));
+                    Date current=new Date();
+                    Date start=new Date();
+                    color = null;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: There is no need to set start or color

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 29]
```diff
@@ -101,14 +117,65 @@ protected void onResume() {
...
+                    upcomingTitle="";
+                    track="";
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Both these assignments are redundant

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 30]
```diff
@@ -101,14 +117,65 @@ protected void onResume() {
...
+                    for (Session s:sorted_sessions){
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Better naming than s

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 31]
```diff
@@ -101,14 +117,65 @@ protected void onResume() {
...
+                        try {
+                            start=DateUtils.getDate(s.getStartTime());
+                        } catch (ParseException e) {
+                            e.printStackTrace();
+                        }
+                        if ((start.after(current))){
+                            upcomingTitle=s.getTitle();
+                            track = s.getTrack().getName().toString();
+                            color = s.getTrack().getColor();
+                            break;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: break in last line of conditional?

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 32]
```diff
@@ -101,14 +117,65 @@ protected void onResume() {
...
+                    track="";
+                    for (Session s:sorted_sessions){
+                        try {
+                            start=DateUtils.getDate(s.getStartTime());
+                        } catch (ParseException e) {
+                            e.printStackTrace();
+                        }
+                        if ((start.after(current))){
+                            upcomingTitle=s.getTitle();
+                            track = s.getTrack().getName().toString();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Name is already a string

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 33]
```diff
@@ -101,14 +117,65 @@ protected void onResume() {
...
+                            color = s.getTrack().getColor();
+                            break;
+                        }
+                    }
+                    if(!upcomingTitle.isEmpty()) {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Use `TextUtils.isEmpty` as suggested before

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 34]
```diff
@@ -101,14 +117,65 @@ protected void onResume() {
...
+                        int trackColor = Color.parseColor(color);
+                        upcomingSessionTitle.setText("Upcoming session: ");
+                        TextDrawable drawable = drawableBuilder.build(String.valueOf(track.charAt(0)), trackColor);
+                        trackImageIcon.setImageDrawable(drawable);
+                        trackImageIcon.setBackgroundColor(Color.TRANSPARENT);
+                        upcomingSessionText.setText(upcomingTitle);
+                    }
+                    else {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Use Java style braces

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 35]
```diff
@@ -101,14 +117,65 @@ protected void onResume() {
...
+                    }
+
                     sessionsListAdapter.notifyDataSetChanged();
 
                     handleVisibility();
                 });
 
         handleVisibility();
     }
+    public void upcomingSessions(){
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Add a new line before the function

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 36]
```diff
@@ -101,14 +117,65 @@ protected void onResume() {
...
+                upcomingSessionText = (TextView) upcomingDialogBox.findViewById(R.id.upcoming_session_textview);
+                upcomingSessionTitle=(TextView) upcomingDialogBox.findViewById(R.id.upcoming_Session_title);
+                Button dialogButton=(Button) upcomingDialogBox.findViewById(R.id.upcoming_button);
+                dialogButton.setOnClickListener(new View.OnClickListener() {
+             @Override
+             public void onClick(View view) {
+                                upcomingDialogBox.dismiss();
+                            }
+         });
+    }
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Correct the indentation

**Review by iamareebjamal — CHANGES_REQUESTED** [review]
Many suggestions from previous reviews are still not completed, please comment on the reviews if there is any discrepancy, otherwise, they'll just get hidden and shown outdated

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java (hunk 26 above)
Comment (mahikaw) [reply android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: The track is being used out of the loop, so it will go out of scope if I declare it in the loop.

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java (hunk 28 above)
Comment (mahikaw) [reply android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: It gives an error otherwise, as I said before.

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 37]
```diff
@@ -101,7 +117,38 @@ protected void onResume() {
...
+                        try {
+                            start = DateUtils.getDate(upcomingSession.getStartTime());
+                        } catch (ParseException e) {
+                            e.printStackTrace();
+                        }
+                        if ((start.after(current))){
+                            upcomingTitle = upcomingSession.getTitle();
+                            track = upcomingSession.getTrack().getName();
+                            color = upcomingSession.getTrack().getColor();
+                        }
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: This if should be inside try block

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 38]
```diff
@@ -101,7 +117,38 @@ protected void onResume() {
...
+                    }
+                    if(!upcomingTitle.isEmpty()) {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Use TextUtils.isEmpty

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 39]
```diff
@@ -101,7 +117,38 @@ protected void onResume() {
         realmRepo.getSessionsByLocation(location)
                 .addChangeListener((sessions, orderedCollectionChangeSet) -> {
                     mSessions.clear();
+                    String upcomingTitle = "";
+                    String track = "";
+                    String color = null;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: There's no need to initialise empty string or explicit nulls to them

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: When using local variables, write them in one line. Codacy issue for per line variables should be for global variables only IMO

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 40]
```diff
@@ -101,7 +117,38 @@ protected void onResume() {
...
                     mSessions.addAll(sessions);
+                    sortedSessions.clear();
+                    sortedSessions.addAll(sessions.sort("startTime"));
+                    Date current = new Date();
+                    Date start = new Date();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: There is no need to initialise start date, it can be declared inside the loop

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 41]
```diff
@@ -101,7 +117,38 @@ protected void onResume() {
...
+                    for (Session upcomingSession:sortedSessions){
+                        try {
+                            start = DateUtils.getDate(upcomingSession.getStartTime());
+                        } catch (ParseException e) {
+                            e.printStackTrace();
+                        }
+                        if ((start.after(current))){
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Extra enclosing brackets

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 42]
```diff
@@ -101,7 +117,38 @@ protected void onResume() {
         realmRepo.getSessionsByLocation(location)
                 .addChangeListener((sessions, orderedCollectionChangeSet) -> {
                     mSessions.clear();
+                    String upcomingTitle = "";
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: This whole block of new change should be in its own function

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java (hunk 39 above)
Comment (mahikaw) [reply android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: @iamareebjamal They need to be declared before because they are being used inside the loop. As I said earlier, it gives an error if I don't initialise them.

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: I am not talking about declaring, but how will it give an error if you don't initialize it. Java initializes variables for you, albeit null

Comment (mahikaw) [reply android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: @iamareebjamal This is the error that it gives when I remove the initialisation. Please correct me if I am doing something wrong.
screen shot 2017-07-10 at 6 43 02 pm

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Hmm Sorry, my mistake, local variables don't have a default type, but I suppose Date start can be moved inside, is it used outside the loop too?

Comment (mahikaw) [reply android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: No it isn't used outside the loop. But isn't it better to declare it outside the loop to avoid the declaration again and again, overtime the loop iterates?

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: If you declare it outside, it's scope leakage. And about the loop, it's already creating a new date object on each iteration

Comment (mahikaw) [reply android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Okay, thanks for the clarification. Did the changes. Please review it once again.

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 43]
```diff
@@ -110,6 +130,55 @@ protected void onResume() {
...
+
+    public void upcomingSession(){
+        String upcomingTitle = "";
+        String track = "";
+        String color = null;
+        Date current = new Date();
+        for (Session sess:sortedSessions){
+            try {
+                Date start;
+                start = DateUtils.getDate(sess.getStartTime());
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Merge these 2 lines

File: android/app/src/main/res/values/strings.xml [hunk 44]
```diff
@@ -72,7 +72,7 @@
     <string name="search">Search</string>
     <string name="share">Share</string>
     <string name="add_to_calendar">Add to Calendar</string>
-
+    <string name="Upcoming">Upcoming</string>
```
Comment (iamareebjamal) [inline android/app/src/main/res/values/strings.xml]: lowercase key

**Review by iamareebjamal — CHANGES_REQUESTED** [review]
Just some minor changes

**Comment by mahikaw** [comment]
@iamareebjamal @the-dagger @shreyasnbhat @Shailesh351 @rohanagarwal94 @arp95 please review this PR.

**Comment by Shailesh351** [comment]
@mahikaw Idea is great. In my opinion we should not add one icon which just show one session and also icon is not for "Upcoming session". User can be confused.

What my thought is to add Sticky headers. There can be three headers `UPCOMING`, `ONGOING`, `FINISHED`. Also it's implementation will be very easy.
Let's see what's others opinon :smile:

**Comment by mahikaw** [comment]
@Shailesh351 Thanks for your opinion. :)
My idea was that the user will be taken to the current session on pressing the icon using the scrolltoposition() of recycler view. This way the user can see the upcoming as well as the current session. This implementation is in addition to the tags that indicate the state of each session at the right hand side..

**Comment by shreyasnbhat** [comment]
@Shailesh351 I think that sticky headers would be nice but it wouldn't look good with the current layout of the Session Card IMO.

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 45]
```diff
@@ -61,11 +74,15 @@
...
     private RealmDataRepository realmRepo = RealmDataRepository.getDefaultInstance();
+    private TextView upcomingSessionText;
+    private TextView upcomingSessionTitle;
+    private TextDrawable.IBuilder drawableBuilder = TextDrawable.builder().round();
 
     @Override
     protected void onCreate(Bundle savedInstanceState) {
 
         super.onCreate(savedInstanceState);
+        upcomingSessionsInitial();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Please change to setUpcomingSessionsDialog()

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 46]
```diff
@@ -110,6 +130,54 @@ protected void onResume() {
...
+                Button dialogButton = (Button) upcomingDialogBox.findViewById(R.id.upcoming_button);
+                dialogButton.setOnClickListener(new View.OnClickListener() {
+                    @Override
+                    public void onClick(View view) {
+                        upcomingDialogBox.dismiss();
+                    }
+                });
+    }
+
+    public void upcomingSession(){
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Please change to setUpcomingSession

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

**Comment by mahikaw** [comment]
@iamareebjamal I have incorporated the changes. Please review it once again.
@the-dagger @niranjan94 @mananwason @rohanagarwal94 @Shailesh351 @shreyasnbhat @arp95 Please review this PR.

File: android/app/src/main/res/values/dimens.xml [hunk 47]
```diff
@@ -91,4 +91,13 @@
     <dimen name="feed_item_corner_radius">3dp</dimen>
     <dimen name="feed_item_border_width">1dp</dimen>
     <dimen name="comment_list_height">300dp</dimen>
+
+    <!--Upcoming dialogbox-->
+    <dimen name="dialog_width">300dp</dimen>
+    <dimen name="upcoming_title_height">50dp</dimen>
+    <dimen name="upcoming_height">70dp</dimen>
+    <dimen name="upcoming_margin_left">30dp</dimen>
```
Comment (Shailesh351) [inline android/app/src/main/res/values/dimens.xml]: Use existing test-size, margin etc. No need to separately define this for particular view.

Comment (mahikaw) [reply android/app/src/main/res/values/dimens.xml]: @Shailesh351 There were no existing margins of the dimensions I required. Same goes for the text size. So I had to add them.

Comment (Shailesh351) [reply android/app/src/main/res/values/dimens.xml]: See https://github.com/mahikaw/open-event-android/blob/ecc76e93253525d60474211121489d28580e09b1/android/app/src/main/res/values/dimens.xml#L44

Comment (arp95) [reply android/app/src/main/res/values/dimens.xml]: please reuse the existing resources. no need to add more.

Comment (mahikaw) [reply android/app/src/main/res/values/dimens.xml]: @Shailesh351 @arp95 done. I have renamed some of the existing attributes to something more generic so that they can be used in future too. Is it okay now?

**Comment by mahikaw** [comment]
@Shailesh351 @arp95 Have incorporated the changes. Please review.
@iamareebjamal @shreyasnbhat @rohanagarwal94 I have just pulled the development branch once more. Please approve it if there's nothing more to change.  Thanks 😄

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 48]
```diff
@@ -110,6 +130,54 @@ protected void onResume() {
...
+                trackImageIcon = (ImageView)upcomingDialogBox.findViewById(R.id.track_image_drawable);
+                upcomingSessionText = (TextView) upcomingDialogBox.findViewById(R.id.upcoming_session_textview);
+                upcomingSessionTitle = (TextView) upcomingDialogBox.findViewById(R.id.upcoming_Session_title);
+                Button dialogButton = (Button) upcomingDialogBox.findViewById(R.id.upcoming_button);
+                dialogButton.setOnClickListener(new View.OnClickListener() {
+                    @Override
+                    public void onClick(View view) {
+                        upcomingDialogBox.dismiss();
+                    }
+                });
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Fix indentation of this block please

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 49]
```diff
@@ -110,6 +130,54 @@ protected void onResume() {
...
+                }
+            } catch (ParseException e) {
+                e.printStackTrace();
+            }
+
+        }
+
+        if(!TextUtils.isEmpty(upcomingTitle)) {
+            int trackColor = Color.parseColor(color);
+            upcomingSessionTitle.setText("Upcoming session: ");
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Use string res

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java [hunk 50]
```diff
@@ -110,6 +130,54 @@ protected void onResume() {
...
+            TextDrawable drawable = drawableBuilder.build(String.valueOf(track.charAt(0)), trackColor);
+            trackImageIcon.setImageDrawable(drawable);
+            trackImageIcon.setBackgroundColor(Color.TRANSPARENT);
+            upcomingSessionText.setText(upcomingTitle);
+        } else {
+            upcomingSessionTitle.setText("No Upcoming sessions");
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Use string res

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

**Comment by mahikaw** [comment]
@iamareebjamal Updated. :)

File: android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java (hunk 48 above)
Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/LocationActivity.java]: Indentation is still not fixed, this should be one indent behind

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

**Comment by mahikaw** [comment]
Fixed it @iamareebjamal . Please approve now.

**Review by iamareebjamal — APPROVED** [review]

**Review by Shailesh351 — APPROVED** [review]

**Review by arp95 — APPROVED** [review]
LGTM.

**Review by rohanagarwal94 — APPROVED** [review]
