### PR TITLE
fix: suppress and fix the warning in EditProfile

### LINKED ISSUE #2421: Suppress and fix the warning in EditProfileActivity
### Bug Report    

**Actual Behaviour**

We get this warning in EditProfileActivity
"Wrong argument count, format string EditProfileActivity requires 0 but format call supplies 1"

**Expected Behaviour**

There should be no warnings

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by nikit19**
Fixes #2421 

Changes: suppress and fix the warning in EditProfile
Screenshots for the change: N/A

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 1]
```diff
@@ -184,6 +185,7 @@ private void showFileChooser() {
         startActivityForResult(Intent.createChooser(intent, "Select Image"), PICK_IMAGE_REQUEST);
     }
 
+    @SuppressLint("TimberArgCount")
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: This is opposite of what we want. Never hide warnings

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 2]
```diff
@@ -212,7 +214,7 @@ protected void onActivityResult(int requestCode, int resultCode, Intent data) {
                     .into(avatar);
         } else if (resultCode == UCrop.RESULT_ERROR) {
             final Throwable cropError = UCrop.getError(data);
-            Timber.d("EditProfileActivity", "UCrop Error" + cropError);
+            Timber.d(cropError, "EditProfileActivity UCrop Error %s");
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Fix this. This should be reverse

Comment (nikit19) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: PR updated. Please review

**Review by iamareebjamal — APPROVED** [review]
