### PR TITLE
fix : Remove compound drawable to support API < 21

### LINKED ISSUE #1867: Compound drawable is not supported in API < 21
**Actual Behaviour**

~Currently in session_item and other places. Drawable is shown using ImageView. 
`<LinearLayout><ImageView/><TextView/><LinearLayout/>`~
Compound drawable is not supported in API < 21

**Expected Behaviour**

~Drawable can be combined with TextView using drawableLeft attribute.
`<TextView  drawableLeft="abc"/>`~
Remove compound drawable to support API < 21

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

[Milestone 14](https://github.com/fossasia/open-event-android/milestone/37)

### PR DESCRIPTION
**Pull request by Shailesh351**
Fixes #1867 

Changes: 
- Removed compound drawable
- Changed AppCompatEditText to TextInputEditText

### CODE REVIEW

**Comment by Shailesh351** [comment]
@iamareebjamal @heysadboy Please review

**Review by iamareebjamal — APPROVED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/auth/UserProfileActivity.java [hunk 1]
```diff
@@ -74,17 +77,17 @@ protected void onCreate(Bundle savedInstanceState) {
             return;
         }
 
-        mTextViewEditProfile.setOnClickListener(v -> {
+        mEditProfile.setOnClickListener(v -> {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/auth/UserProfileActivity.java:80]: Can you please open an issue to change these from hungarian notation?

**Review by scandindian — APPROVED** [review]
Not crashing on API < 21 now, works fine.
