### PR TITLE
Fix #1973 added more functionality to About fragment

### LINKED ISSUE #1973: Adding more functionality in the About fragment
**Actual Behaviour**

Currently nothing happens when the user clicks on the event date or on the event location

**Expected Behaviour**

On clicking on the event date it should open up in the calendar and give the user the option to save the event.

On clicking on the event location, map fragment should open showing the location of the event.

**Steps to reproduce it**

Just open the app and try clicking on the event date or location

**Screenshots of the issue**
screenshot_20171103-021929

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by nikit19**
Fixes #1973 

Changes: On clicking on the event location,the location will open up in the location fragment and on clicking on the event date, it will open up in the calendar for the user to save the event date 

Screenshots for the change: 
ezgif com-video-to-gif 18

### CODE REVIEW

**Comment by nikit19** [comment]
@heysadboy Currently travis CI is failing because it is not able to find OSMapFragment because it is present in the fdroid directory. I tried shifting it from fdroid directory to the main directory and the app works perfectly. Can you please tell me if this is the right way to solve this problem?

**Comment by scandindian** [comment]
@nikit19 Did you check MapFragment in Google Play folder?

**Comment by nikit19** [comment]
@heysadboy I tried using that instead of OSMapFragment and got the error cannot resolve symbol MapsFragment
screenshot from 2017-11-10 22-14-40

**Comment by scandindian** [comment]
@nikit19 Do it like this to intitialize map fragment,
```
Bundle bundle = new Bundle();
                bundle.putBoolean(ConstantStrings.IS_MAP_FRAGMENT_FROM_MAIN_ACTIVITY, true);
                Fragment mapFragment = ((OpenEventApp)getApplication())
                        .getMapModuleFactory()
                        .provideMapModule()
                        .provideMapFragment();
                mapFragment.setArguments(bundle);
               
```
Check the click any other way if not from matching instance of the fragment.

**Comment by nikit19** [comment]
@heysadboy done with the requested changes but I ran into a problem. I pulled the latest changes into my local repository and tried to squash my last commit. As a result the latest commits are also included in this PR. Can you please help me ? Should I squash all the latest commits?

**Comment by scandindian** [comment]
@nikit19 Only squash your commits ~

**Comment by nikit19** [comment]
@heysadboy thanks! I updated the branch and now only my changes are visible. Now you can review.
Thank you!

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java [hunk 1]
```diff
@@ -110,6 +121,33 @@ public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
...
+
+        eventDate.setOnClickListener(v -> {
+            Intent intent = new Intent(Intent.ACTION_INSERT);
+            intent.setType("vnd.android.cursor.item/event");
+            intent.putExtra(CalendarContract.Events.TITLE, event.getName());
+            intent.putExtra(CalendarContract.Events.DESCRIPTION, event.getDescription());
+            intent.putExtra(CalendarContract.EXTRA_EVENT_BEGIN_TIME, DateConverter.formatDateWithDefault(DateConverter.FORMAT_24H, event.getStartsAt()));
+            intent.putExtra(CalendarContract.EXTRA_EVENT_END_TIME, DateConverter.formatDateWithDefault(DateConverter.FORMAT_24H, event.getEndsAt()));
+            startActivity(intent);
+        });
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: The data flow is off. Why do we need to persist data in sharedpreferences to communicate between app components? Besides, this can moved to a util class

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java (hunk 1 above)
Comment (nikit19) [reply android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: @iamareebjamal  data no longer persists in sharedPreference as it gets cleared and I have moved that calendar code to the Util class. Please review

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java [hunk 2]
```diff
@@ -110,6 +121,33 @@ public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
...
+
+        });
+
+        eventDate.setOnClickListener(v -> {
+            String eventName = event.getName();
+            String eventDescription = event.getDescription();
+            String startTime = event.getStartsAt();
+            String endTime = event.getEndsAt();
+            Context context = getActivity();
+            Utils.eventCalendar(context, eventName, eventDescription, startTime, endTime);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: Instead of these many parameters, please pass event in the Utils function

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java [hunk 3]
```diff
@@ -562,22 +562,30 @@ private void doMenuAction(int menuItemId) {
 
     @Override
     public void onBackPressed() {
+        Fragment fragment = getSupportFragmentManager().findFragmentById(R.id.content_frame);
+        boolean mapFragment = SharedPreferencesUtil.getBoolean(ConstantStrings.IS_MAP_FRAGMENT_FROM_MAIN_ACTIVITY, false);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: I meant this shouldn't be needed. This can be done in memory

File: android/app/src/main/java/org/fossasia/openevent/utils/Utils.java [hunk 4]
```diff
@@ -185,6 +187,17 @@ public static String getSocialLinkName(String link) {
...
+    public static void eventCalendar(Context context, String name, String description, String startTime, String endTime) {
+
+        Intent intent = new Intent(Intent.ACTION_INSERT);
+        intent.setType("vnd.android.cursor.item/event");
+        intent.putExtra(CalendarContract.Events.TITLE, name);
+        intent.putExtra(CalendarContract.Events.DESCRIPTION, description);
+        intent.putExtra(CalendarContract.EXTRA_EVENT_BEGIN_TIME, DateConverter.formatDateWithDefault(DateConverter.FORMAT_24H, startTime));
+        intent.putExtra(CalendarContract.EXTRA_EVENT_END_TIME, DateConverter.formatDateWithDefault(DateConverter.FORMAT_24H, endTime));
+        context.startActivity(intent);
+    }
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/utils/Utils.java]: Create intent and return from this function and call `startActivity` in the caller itself. The you won't need to pass context as a parameter

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java (hunk 3 above)
Comment (nikit19) [reply android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: @iamareebjamal  can you please tell me what should I use to communicate this message from fragment to activity?

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: Activity can implement an interface whose instance will be passed in Fragment. Like callbacks in javascript

**Comment by nikit19** [comment]
@iamareebjamal done with all the requested changes.Please review.
Thank you.

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java [hunk 5]
```diff
@@ -107,7 +107,7 @@
 import io.realm.RealmResults;
 import timber.log.Timber;
 
-public class MainActivity extends BaseActivity implements FeedAdapter.AdapterCallback {
+public class MainActivity extends BaseActivity implements FeedAdapter.AdapterCallback,AboutFragment.OnMapSelectedListener {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: Please add space after `,`

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java [hunk 6]
```diff
@@ -99,9 +109,15 @@
     private RealmResults<Session> bookmarksResult;
     private List<Object> sessions = new ArrayList<>();
     private List<SocialLink> socialLinks = new ArrayList<>();
+    private static final String FRAGMENT_TAG_REST = "fgtr";
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: Please use a more meaningful TAG name and value

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java [hunk 7]
```diff
@@ -99,9 +109,15 @@
...
 
     private RealmDataRepository realmRepo = RealmDataRepository.getDefaultInstance();
     private Event event;
+    OnMapSelectedListener mCallback;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: This can be private, and please don't use hungarian notation

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java [hunk 8]
```diff
@@ -318,6 +358,23 @@ public void onResume() {
...
+    @Override
+    public void onAttach(Activity activity) {
+        super.onAttach(activity);
+
+        try {
+            mCallback = (OnMapSelectedListener) activity;
+        } catch (ClassCastException e) {
+            throw new ClassCastException(activity.toString()
+                    + "must implement OnMapSelectedListener");
+        }
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: This isn't correct, the activity should explicitly pass its instance to the fragment through a method or `newInstance` static creator with concrete type of `OnMapSelectedListener`

This way we are not casting stuff in a statically compiled language.

Fragment should also check the nullability of the listener instance before calling it

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java (hunk 8 above)
Comment (nikit19) [reply android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: @iamareebjamal Can you please explain how to achieve the first part?
I am not able to understand 
And I get a null pointer exception when I check the nullability of the listener in the try block.
Other than this I have made all the other changes that you asked
Thank you

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: This `onAttach` block should be removed. The activity should pass `this` i.e. the instance of `OnMapSelectedListener` to the Fragment when it is creating the fragment. So instead of `new Fragment()`, use a static method in fragment `newInstance(OnMapSelectedListener)` which will be called by the activity and will set the mapSelectedListener in the fragment

Wherever there'll be a call on listener, you'll have to check if it is null first

**Comment by dr0pdb** [comment]
@nikit19 Is there any particular reason why this isn't updated ? If not, then please update it and let's get it merged.

**Comment by nikit19** [comment]
@srv-twry I had my exams when I was working on this PR and thought of updating it later.
 I will update this PR soon

**Comment by nikit19** [comment]
@iamareebjamal Updated the PR with the requested changes.
Please review

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java [hunk 9]
```diff
@@ -110,7 +110,8 @@
 import io.realm.RealmResults;
 import timber.log.Timber;
 
-public class MainActivity extends BaseActivity implements FeedAdapter.OpenCommentsDialogListener, OnImageZoomListener {
+
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: Please remove extra line

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java [hunk 10]
```diff
@@ -142,6 +144,12 @@
     private CompositeDisposable disposable;
     private RealmDataRepository realmRepo = RealmDataRepository.getDefaultInstance();
     private Event event; // Future Event, stored to remove listeners
+    private AboutFragment.OnMapSelectedListener onMapSelectedListener =new AboutFragment.OnMapSelectedListener() {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: Add space after =, use lambda

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java [hunk 11]
```diff
@@ -879,6 +892,9 @@ public void openCommentsDialog(List<CommentItem> commentItems) {
     }
 
     @Override
+    public void onMapSelected(boolean value) {
+        //it is used to check if the maps fragment is selected
+    }
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java:891]: Add new line below

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java [hunk 12]
```diff
@@ -101,8 +108,14 @@
...
     private List<Object> sessions = new ArrayList<>();
     private List<SocialLink> socialLinks = new ArrayList<>();
+    private static final String MAP_FRAGMENT_TAG = "mapFragment";
 
     private Event event;
+    private static OnMapSelectedListener mapFragmentCallback;
+
+    public interface OnMapSelectedListener {
+        public void onMapSelected(boolean value);
+    }
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java:118]: Add new line below

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java [hunk 13]
```diff
@@ -113,6 +126,31 @@ public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
...
+                if (mapFragmentCallback != null)
+                    mapFragmentCallback.onMapSelected(true);
+            }
+        });
+
+        eventDate.setOnClickListener(v -> {
+            if (event.isValid())
+                startActivity(Utils.eventCalendar(event));
+
+        });
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: Remove a line from above and add below

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java [hunk 14]
```diff
@@ -132,6 +170,12 @@ public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
         });
     }
 
+    public static AboutFragment newInstance(OnMapSelectedListener onMapSelectedListener) {
+        AboutFragment fragment = new AboutFragment();
+        mapFragmentCallback=onMapSelectedListener;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: Add spaces

**Review by iamareebjamal — CHANGES_REQUESTED** [review]
Please check formatting after pushing the commit. It distracts from real issue. There is lenient build proccess on this project as compared to Orga App where a single lint error or bad practice fails the entire build

**Comment by nikit19** [comment]
@iamareebjamal really sorry about the formatting errors. won't happen from next time.
Please review

**Review by iamareebjamal — APPROVED** [review]
