### PR TITLE
Download Latest Data bug fix

### LINKED ISSUE #2175: Nothing happens on selecting DownloadLatestData in menu
**Actual Behaviour**

Selecting DownloadLatestData menu item does nothing once the data has been downloaded.

**Expected Behaviour**

It should show the data fetch dialog.

**Would you like to work on the issue?**

Yes

@iamareebjamal am not sure if it has been made that way !?

### PR DESCRIPTION
**Pull request by simarsingh24**
Fixes #2175

### CODE REVIEW

**Review by dr0pdb — APPROVED** [review]

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java [hunk 1]
```diff
@@ -254,6 +256,7 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 displaySpeakersCallInformation();
                 break;
             case R.id.action_download_latest_data:
+                SharedPreferencesUtil.putBoolean(ConstantStrings.IS_DOWNLOAD_DONE, false);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: This is not the correct way. Download may be done. Saving the wrong information is ... wrong. Simply show the dialog even if the data is downloaded, i.e., don't check if it is downloaded. 

Second this you would have to do is that currently, if user denies to download latest data, it is loaded from JSON. But if the data is already downloaded, it should not be loaded from JSON, so when handling negative response, add the check if the data is downloaded. If it is not, then load from JSON, otherwise do nothing

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java (hunk 1 above)
Comment (simarsingh24) [reply android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: @iamareebjamal Yeah true! Should I create a separate method that will take into account everything you mentioned then?

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: Yes

**Comment by simarsingh24** [comment]
@iamareebjamal please review

**Comment by iamareebjamal** [comment]
There is too much repetition of code. Try to reduce it

**Comment by simarsingh24** [comment]
@iamareebjamal yeah I also felt that, a better approach would be passing a boolean `needChecking` to the original `downloadData()` which would decide wether to check from  SharedPreference or not ! what do you say?

**Comment by iamareebjamal** [comment]
Simply make a method which unconditionally shows a dialog, and where we don't need to show it, add the check before calling

**Comment by simarsingh24** [comment]
Changes: now `downloadData` shows dialog irrespective of the `IS_DOWNLOAD_DONE` status, which is taken care by calling function now.

**Review by iamareebjamal — APPROVED** [review]

**Review by mayank8318 — APPROVED** [review]
