### PR TITLE
fix: added support for font color attribute

### LINKED ISSUE #1705: Add support for font colors in tracks
**Actual Behaviour**

Currently, Track model does not contain font color

**Expected Behaviour**

Add support for font color in model and UI both and add corresponding migration in realm database
**The font color must be HTML compliant**

**Would you like to work on the issue?**

No

### PR DESCRIPTION
**Pull request by arp95**
Fixes #1705 
Changes: 
added support for font_color attribute. For lighter color replacing text with black color as opposed to white.

Screenshots for the change: 

-

@iamareebjamal @Shailesh351 @shreyasnbhat @mahikaw @rohanagarwal94 
please review.

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java [hunk 1]
```diff
@@ -228,10 +228,14 @@ public void onBindViewHolder(final SessionViewHolder holder, final int position)
             default:
         }
 
-        if(session.isBookmarked()) {
+        if(session.isBookmarked() && (Color.parseColor(session.getTrack().getFontColor()) == Color.WHITE)) {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: No need to do this, we are using vector icons, tint the icon instead. Look at Views `setTint` method

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java (hunk 1 above)
Comment (arp95) [reply android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: having a look.

Comment (arp95) [reply android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: @iamareebjamal 
but how will i check the font color? shouldnt this be fine?

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: But why including a black and white icon? You can tint it. And no need to check if color is white or black. Just tint the icon with font color

Comment (arp95) [reply android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: fine then.
also should i do the same for search icon and app bar title? or should i leave them for now.

**Comment by arp95** [comment]
@iamareebjamal please review now.

File: android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java [hunk 2]
```diff
@@ -233,6 +234,7 @@ public void onBindViewHolder(final SessionViewHolder holder, final int position)
         } else {
             holder.sessionBookmarkIcon.setImageResource(R.drawable.ic_bookmark_border_white_24dp);
         }
+        DrawableCompat.setTint(holder.sessionBookmarkIcon.getDrawable(), ContextCompat.getColor(context, Integer.valueOf(session.getTrack().getFontColor())));
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: This is wrong. It is supposed to work like this :- 

ContextCompat.getColor(context, R.color.white);

And you are using it this way :- 

ContextCompat.getColor(context, Integer.valueOf("#ffffff"));

This will unanimously crash always

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: There's a setTint method in Views class I guess, please take a look there

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java (hunk 2 above)
Comment (arp95) [reply android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: @iamareebjamal 
but how to i access the R.color when the value is to be taken from json file?

Comment (arp95) [reply android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: looking at that.

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java]: Don't access R.color. Just tint with `Color.parseColor(fontcolorstring)`

**Comment by arp95** [comment]
@iamareebjamal @Shailesh351 @shreyasnbhat @rohanagarwal94 
please review.

**Comment by arp95** [comment]
@iamareebjamal @rohanagarwal94 @Shailesh351 @shreyasnbhat 
please review.

**Comment by arp95** [comment]
19551701_10211705596709906_1094188451_o

**Comment by arp95** [comment]
@iamareebjamal 
shoudl the back arrow color be also changed. If yes then i need to provide a drawable right?

**Comment by arp95** [comment]
@Shailesh351 
there is no way to change the back button color programmatically?
i tried finding but none seems to work.

**Comment by iamareebjamal** [comment]
@arp95 
````Java
Drawable upArrow = ContextCompat.getDrawable(context, R.drawable.abc_ic_ab_back_mtrl_am_alpha);
upArrow.setColorFilter(ContextCompat.getColor(context, R.color.white), PorterDuff.Mode.SRC_ATOP);
getSupportActionBar().setHomeAsUpIndicator(upArrow);
````

**Comment by arp95** [comment]
@iamareebjamal 
i tired this. but this drawable is not getting recognized. can you check on your end and see whether its working or not?

**Comment by iamareebjamal** [comment]
@arp95 The new drawable name is this `abc_ic_ab_back_material`

**Comment by arp95** [comment]
@iamareebjamal @Shailesh351 @shreyasnbhat 
please review now.

**Comment by arp95** [comment]
i had to use color white for location and speaker fragment as they were automatically turning black. rest have handled the edge cases which i could figure out.

**Comment by arp95** [comment]
screenshot_20170629-155122

screenshot_20170629-155115

screenshot_20170629-155127

screenshot_20170629-155216

**Review by Shailesh351 — APPROVED** [review]

**Comment by arp95** [comment]
@mariobehling @the-dagger 
please review.

**Comment by iamareebjamal** [comment]
@arp95 In Marshmallow+, you can tint the status bar icons as well

**Comment by arp95** [comment]
doing it.

**Comment by arp95** [comment]
@iamareebjamal please review now.

**Review by iamareebjamal — APPROVED** [review]
