### PR TITLE
fix: disabled back button for Map Fragment in tablet view

### LINKED ISSUE #1720: Back arrow is enabled for Google Play Variant in Tablet mode
**Actual Behaviour**

The back arrow is shown in Tablet mode in Google Map variant in Maps Fragment

**Expected Behaviour**

The back arrow should be hidden 

**Screenshots of the issue**

device-2017-06-17-205241

**Would you like to work on the issue?**

@arp95 Please fix

### PR DESCRIPTION
**Pull request by arp95**
Fixes #1720 

Changes: 
Disabled back button for Map Fragment for tablet view of the app.

Screenshots for the change: 
19264107_10211597374164410_1936271897_o

### CODE REVIEW

**Comment by arp95** [comment]
@iamareebjamal @Shailesh351 @shreyasnbhat @rohanagarwal94 
please review.

File: android/app/src/googleplay/java/org/fossasia/openevent/fragments/MapsFragment.java [hunk 1]
```diff
@@ -49,6 +52,7 @@
     private GoogleMap mMap;
     private Marker locationMarker;
     private List<String> searchItems = new ArrayList<>();
+    private SharedPreferences sharedPreferences;
```
Comment (iamareebjamal) [inline android/app/src/googleplay/java/org/fossasia/openevent/fragments/MapsFragment.java]: Don't use sharedpreference please. This should not be persisted

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/googleplay/java/org/fossasia/openevent/fragments/MapsFragment.java (hunk 1 above)
Comment (arp95) [reply android/app/src/googleplay/java/org/fossasia/openevent/fragments/MapsFragment.java]: sure. looking for another way.

Comment (arp95) [reply android/app/src/googleplay/java/org/fossasia/openevent/fragments/MapsFragment.java]: @iamareebjamal 
i am using the Utils class then and creating getters and setters to get the value? is it fine?

Comment (iamareebjamal) [reply android/app/src/googleplay/java/org/fossasia/openevent/fragments/MapsFragment.java]: Sure

**Review by iamareebjamal — APPROVED** [review]

**Review by Shailesh351 — APPROVED** [review]

**Review by shreyasnbhat — APPROVED** [review]
Looks Good

**Comment by iamareebjamal** [comment]
Is there some bug in Travis or what

**Comment by iamareebjamal** [comment]
Not even getting triggered on close and reopen

**Comment by the-dagger** [comment]
@iamareebjamal Travis ran and the check passed successfully already.
