### PR TITLE
Fix #1987-Give option to undo in Tracks section.

### LINKED ISSUE #1987: No option to undo Bookmark change in the Tracks section
**Actual Behaviour**

Currently the Snackbar in Tracks when a bookmark is added or removed does not have an UNDO action.

**Expected Behaviour**

There should be an UNDO action like the one in Bookmarks section.

**Steps to reproduce it**

Open Tracks
Select any option
Bookmark / Remove bookmark for any event.

**Screenshots of the issue**

image

image

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by mayank8318**
Fixes #1987 

Changes: Provide undo button in the snackbar.

Screenshots for the change: 
image

image

### CODE REVIEW

**Review by dr0pdb — APPROVED** [review]

**Review by the-dagger — DISMISSED** [review]
Let's implement the snacker properly here.
Ideally it shouldn't be obstructing the FAB as shown in the screenshot, instead use CoordinatorLayout as parent and pass it to your snacker's view.

Ref : https://stackoverflow.com/a/32777587/5471095

**Comment by mayank8318** [comment]
@the-dagger Actually since the snackbar is used in the view holder, we cannot access the Coordinator Layout. @nikit19 is trying to solve it in PR #1992 .

**Comment by iamareebjamal** [comment]
@mayank8318  Status? We have a lot of PRs here which are almost complete and unmerged. Let's help clean the backlog up.

The ViewHolder can let the adapter know when to show the snackbar and the adapter can tell the fragment or activity the same through callback interface

We can have discussions on implementation here if there's a problem

**Comment by mayank8318** [comment]
@iamareebjamal Sorry for the delay I was waiting for the other PR to solve it since it is on this particular issue.
Need help here - 
I made an interface for callback in the `DayScheduleAdapter` but here the problem is I have to pass the callback between fragments. So I made the interface extend `Serializable` and passed the callback as an argument in a bundle. But I get null value for the object. What am I doing wrong here?

public static DayScheduleFragment getInstance(DayScheduleAdapter.DayScheduleCallback dayScheduleCallback)
    {
        DayScheduleFragment f = new DayScheduleFragment();
        Bundle args = new Bundle();
        args.putSerializable("callback", dayScheduleCallback);
        f.setArguments(args);
        return f;
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        date = getArguments().getString(ConstantStrings.EVENT_DAY, "");
        dayScheduleCallback = (DayScheduleAdapter.DayScheduleCallback) getArguments().getSerializable("callback");
    }

**Comment by iamareebjamal** [comment]
You don't need to send it in Bundle. Actually there's no pattern where an object to be used as a listener should be serialized and sent. Only data objects should be serialized. Secondly, when you serialize the object and deserialize it, the object reference is not the same, a new object is created, so the callback won't even work.

Also, if the interface implementer is the whole activity, then you are serializing the whole activity and then sending which is a huge memory leak

You can simply add a setter in fragment and pass the interface implementation there

**Comment by mayank8318** [comment]
Changes : Adjust for FAB so that Snackbar doesn't overlap with it.
image

@iamareebjamal Please review :)

File: android/app/src/main/java/org/fossasia/openevent/adapters/DayScheduleAdapter.java [hunk 1]
```diff
@@ -29,18 +30,28 @@
...
     private String eventDate;
+    private DayScheduleCallback dayScheduleCallback;
 
     private RealmDataRepository realmRepo = RealmDataRepository.getDefaultInstance();
 
     private ArrayList<String> tracks = new ArrayList<>();
     private List<Session> copyOfSessions = new ArrayList<>();
 
-    public DayScheduleAdapter(List<Session> sessions, Context context) {
+    public interface DayScheduleCallback {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/adapters/DayScheduleAdapter.java]: Please rename to a proper name, like OnBookmarkSelectedListener

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/adapters/DayScheduleAdapter.java]: Also this is used in places other than DayScheduleAdapter, so move to its own class

File: android/app/src/main/java/org/fossasia/openevent/adapters/DayScheduleAdapter.java [hunk 2]
```diff
@@ -29,18 +30,28 @@
...
+        void showSnackbar(int toDisplayResource, int length, int actionCode, int sessionId, ImageButton slot_bookmark, int colorCode);
+    }
+
+    public DayScheduleAdapter(List<Session> sessions, Context context, DayScheduleCallback dayScheduleCallback) {
         super(sessions);
         this.copyOfSessions = new ArrayList<>(sessions);
         this.context = context;
+        this.dayScheduleCallback = dayScheduleCallback;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/adapters/DayScheduleAdapter.java]: Remove from constructor and add a setter instead

File: android/app/src/main/java/org/fossasia/openevent/adapters/GlobalSearchAdapter.java [hunk 3]
```diff
@@ -36,10 +37,11 @@
     private final int DIVIDER = 4;
     private final int SESSION = 5;
 
-    public GlobalSearchAdapter(List<Object> dataList, Context context) {
+    public GlobalSearchAdapter(List<Object> dataList, Context context, DayScheduleAdapter.DayScheduleCallback dayScheduleCallback) {
         super(dataList);
         this.context = context;
         this.filteredResultList = dataList;
+        this.dayScheduleCallback = dayScheduleCallback;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/adapters/GlobalSearchAdapter.java]: Same here

File: android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java [hunk 4]
```diff
@@ -89,50 +94,34 @@ public void bindSession(RealmDataRepository realmRepo){
...
-                                    slot_bookmark.setImageResource(R.drawable.ic_bookmark_white_24dp);
-
-                                    WidgetUpdater.updateWidget(context);
-                                })
-                                .setActionTextColor(ColorUtils.setAlphaComponent(Views.getAccentColor(context), 220));
-                        snackbar.show();
-                    } else {
-                        Snackbar.make(slot_content, R.string.removed_bookmark, Snackbar.LENGTH_SHORT).show();
-                    }
+                    dayScheduleCallback.showSnackbar(R.string.removed_bookmark, Snackbar.LENGTH_LONG, CODE_UNDO_REMOVED, sessionId, slot_bookmark, storedColor);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java]: Check for null before calling the callback

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java]: Please reduce the arguments amount to at most 2. We don't need to pass the snack bar length and string resource to be used. It should just have id and information that it was removed or added, which can be expressed through a boolean

File: android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java [hunk 5]
```diff
@@ -89,50 +94,34 @@ public void bindSession(RealmDataRepository realmRepo){
...
+            slot_bookmark.setColorFilter(storedColor, PorterDuff.Mode.SRC_ATOP);
 
             final int sessionId = session.getId();
 
             slot_bookmark.setOnClickListener(v -> {
-                if(session.getIsBookmarked()) {
+                if (session.getIsBookmarked()) {
 
                     realmRepo.setBookmark(sessionId, false).subscribe();
                     slot_bookmark.setImageResource(R.drawable.ic_bookmark_border_white_24dp);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java]: Also, please change this to camel case while you're at it

File: android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java [hunk 6]
```diff
@@ -235,5 +250,30 @@ public void onDestroyView() {
...
+                slot_bookmark.setImageResource(R.drawable.ic_bookmark_white_24dp);
+                slot_bookmark.setColorFilter(colorCode, PorterDuff.Mode.SRC_ATOP);
+
+                WidgetUpdater.updateWidget(getContext());
+            })
+                    .setActionTextColor(ColorUtils.setAlphaComponent(Views.getAccentColor(getContext()), 220));
+        }
+
+        snackbar.show();
+    }
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java]: This code is almost same everywhere, shouldn't this be handled in just one place, the activity?

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java (hunk 6 above)
Comment (mayank8318) [reply android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java]: @iamareebjamal  Sorry didn't get you. Do you mean like a helper function for making the Snackbar?

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java]: I mean if there is no change, and it only occurs in a single fragment hierarchy, why can't it be handled in a single place

File: android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java (hunk 5 above)
Comment (mayank8318) [reply android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java]: Can't find that method and if I refactor it here it treats it as a variable "isBookmarked" which is part of Session Realm Object

File: android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java (hunk 4 above)
Comment (mayank8318) [reply android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java]: @iamareebjamal We will still need the reference to slot_bookmark right? Should I pass the view holder itself as then I dont need to pass color, session etc

File: android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java (hunk 6 above)
Comment (mayank8318) [reply android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java]: @iamareebjamal We need to pass the parentView in each fragment while making the Snackbar. So I can make a helper method where I pass the view from the fragments and the rest of the code is the same everywhere. Didnt know if this was good practice or not. Should I do it like this?
It is done similarly in Phimpe if I am not wrong.

File: android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java (hunk 4 above)
Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java]: Create an Object with these parameters and send it instead. Sounds good?

File: android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java (hunk 6 above)
Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java]: Yup, if the code depends on each fragment's layout, then create a helper method for all the similar code

File: android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java (hunk 4 above)
Comment (mayank8318) [reply android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java]: Yep cool

**Comment by mayank8318** [comment]
@iamareebjamal Please review :)

File: android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java (hunk 5 above)
Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java]: I'm talking about `slot_bookmark` variable

Comment (mayank8318) [reply android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java]: Done

File: android/app/src/main/java/org/fossasia/openevent/SnackbarHelper.java [hunk 7]
```diff
@@ -0,0 +1,31 @@
+package org.fossasia.openevent;
+
+import android.widget.ImageButton;
+
+/**
+ * Created by mayank on 14/1/18.
+ */
+public class SnackbarHelper {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/SnackbarHelper.java]: Please remove author comments and move to appropriate package

File: android/app/src/main/java/org/fossasia/openevent/SnackbarHelper.java [hunk 8]
```diff
@@ -0,0 +1,31 @@
...
+        return imageButton;
+    }
+
+    public int getStoredColor() {
+        return storedColor;
+    }
+
+    public int getSessionId() {
+        return sessionId;
+    }
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/SnackbarHelper.java]: Instead of generated getters, use Lombok `@Data` annotation

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 9]
```diff
@@ -232,5 +238,10 @@ public void handleVisibility() {
             searchRecyclerView.setVisibility(View.VISIBLE);
         }
     }
+
+    @Override
+    public void showSnackbar(int actionCode, SnackbarHelper snackbarHelper) {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Encapsulate `actionCode` inside object itself. Change int to enum, rename SnackbarHelper to `BookmarkStatus`

File: android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java [hunk 10]
```diff
@@ -173,10 +169,13 @@ public void bindSession(RealmDataRepository realmRepo){
             Timber.d("This session has no track somehow : " + session + " " + sessionTrack);
         }
 
-        if(session.getMicrolocation() != null) {
+        if (session.getMicrolocation() != null)
+
+        {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/adapters/viewholders/DayScheduleViewHolder.java]: Please correct the syntax of all above if and elses

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java [hunk 11]
```diff
@@ -134,6 +140,7 @@ public void onEventLoaded(EventLoadedEvent eventLoadedEvent) {
     private void setUpBookmarksRecyclerView() {
         bookmarksRecyclerView.setVisibility(View.VISIBLE);
         bookMarksListAdapter = new GlobalSearchAdapter(sessions, getContext());
+        bookMarksListAdapter.setOnBookmarkSelectedListener(this);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java:143]: Remove the listeners on destroy in each fragment/activity

File: android/app/src/main/java/org/fossasia/openevent/listeners/OnBookmarkSelectedListener.java [hunk 12]
```diff
@@ -0,0 +1,16 @@
+package org.fossasia.openevent.listeners;
+
+import org.fossasia.openevent.SnackbarHelper;
+
+/**
+ * Created by mayank on 13/1/18.
+ */
+
+public interface OnBookmarkSelectedListener {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/listeners/OnBookmarkSelectedListener.java]: Remove author comment

File: android/app/src/main/java/org/fossasia/openevent/utils/SnackbarUtil.java [hunk 13]
```diff
@@ -0,0 +1,52 @@
...
+        else if (actionCode == CODE_ERROR)
+            toDisplayResource = R.string.error_create_notification;
+        else
+            toDisplayResource = R.string.added_bookmark;
+
+        Snackbar snackbar = Snackbar.make(view, toDisplayResource, Snackbar.LENGTH_LONG);
+        if (actionCode == CODE_UNDO_ADDED) {
+            snackbar = snackbar.setAction(R.string.undo, view1 -> {
+                RealmDataRepository.getDefaultInstance().setBookmark(snackbarHelper.getSessionId(), false).subscribe();
+                snackbarHelper.getImageButton().setImageResource(R.drawable.ic_bookmark_white_24dp);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/utils/SnackbarUtil.java]: We only need the snackbar stuff to be handled in this utility class, passing foreign views is bad. Handle what can be handled locally, there itself, create a common static method in `Views` if you need to, but only pass absolutely needed stuff to the listener. I think the only thing needed to pass is the action type and the id of the session.

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

**Comment by mayank8318** [comment]
@iamareebjamal Please review :)
Can't find a solution for the Codacy issue. Any suggestions there?

File: android/app/src/main/java/org/fossasia/openevent/status/BookmarkStatus.java [hunk 14]
```diff
@@ -0,0 +1,18 @@
+package org.fossasia.openevent.status;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/status/BookmarkStatus.java]: A new package is not needed, just add it in the same package as its listener. The coupling between components should be reflected by the packaging

File: android/app/src/main/java/org/fossasia/openevent/status/BookmarkStatus.java [hunk 15]
```diff
@@ -0,0 +1,18 @@
...
+import org.fossasia.openevent.listeners.OnBookmarkSelectedListener;
+
+import lombok.AllArgsConstructor;
+import lombok.Data;
+
+@Data
+@AllArgsConstructor
+public class BookmarkStatus {
+
+    private ImageButton imageButton;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/status/BookmarkStatus.java]: Why can't we handle the image button locally, why do we need to send it in a listener? We should only propagate data, not views.

File: android/app/src/main/java/org/fossasia/openevent/status/BookmarkStatus.java [hunk 16]
```diff
@@ -0,0 +1,18 @@
...
+    private int storedColor;
+    private int sessionId;
+    private OnBookmarkSelectedListener.Status actionCode;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/status/BookmarkStatus.java]: Move the status out of listener, you may add it in this class instead. Listener should be pure interface

File: android/app/src/main/java/org/fossasia/openevent/utils/SnackbarUtil.java [hunk 17]
```diff
@@ -0,0 +1,51 @@
...
+
+import static org.fossasia.openevent.listeners.OnBookmarkSelectedListener.Status.CODE_ERROR;
+import static org.fossasia.openevent.listeners.OnBookmarkSelectedListener.Status.CODE_UNDO_ADDED;
+import static org.fossasia.openevent.listeners.OnBookmarkSelectedListener.Status.CODE_UNDO_REMOVED;
+
+public class SnackbarUtil {
+    public static Snackbar setSnackbarAction(Context context, Snackbar snackbar, BookmarkStatus bookmarkStatus) {
+
+        if (bookmarkStatus.getActionCode() == CODE_UNDO_ADDED) {
+            snackbar = snackbar.setAction(R.string.undo, view1 -> {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/utils/SnackbarUtil.java]: You don't need to reassign `snackbar`. It is not an immutable type like String

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/status/BookmarkStatus.java (hunk 15 above)
Comment (mayank8318) [reply android/app/src/main/java/org/fossasia/openevent/status/BookmarkStatus.java]: `slotBookmark` belongs to the viewholder, so I cannot access it outside without passing it. Or I will have to access the view holder somehow.

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/status/BookmarkStatus.java]: Why do you need to access it in the listener implementation?

Comment (mayank8318) [reply android/app/src/main/java/org/fossasia/openevent/status/BookmarkStatus.java]: I need to update the UI in the snackbar action for undo.

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/status/BookmarkStatus.java]: When you undo, the view is updated again, right? So it can be updated there

**Review by iamareebjamal — APPROVED** [review]
Great work :smile:
