### PR TITLE
fix : profile pic error fixed

### LINKED ISSUE #2416: App crashes whenever Profile picture is updated
**Actual Behaviour**

The app crashes whenever the profile picture is updated in our account (irrespective of its size)

**Expected Behaviour**

The crash should not occur

**Steps to reproduce it**

->Open the app
->Log in 
->Update profile settings
->Update Profile Image

**LogCat for the issue**
`E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
                                                                        Process: org.fossasia.openevent, PID: 18873
                                                                        java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                            at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                            at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                         Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=18873, uid=10273 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                                            at android.os.Parcel.readException(Parcel.java:1620)
                                                                            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                            at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
                                                                            at android.content.ContentResolver.query(ContentResolver.java:491)
                                                                            at android.content.ContentResolver.query(ContentResolver.java:434)
                                                                            at com.yalantis.ucrop.util.FileUtils.getDataColumn(FileUtils.java:109)
                                                                            at com.yalantis.ucrop.util.FileUtils.getPath(FileUtils.java:183)
                                                                            at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:171)
                                                                            at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:90)
                                                                            at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:41)
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                            at java.lang.Thread.run(Thread.java:818) `

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by dreadpool2**
Fixes #2416 

Changes: 
Used `PackageManager` for External Storage permissions in `EditProfileActivity`
A permission dialog is visible once the user enters the profile details page.

### CODE REVIEW

**Review by nikit19 — CHANGES_REQUESTED** [review]
Please see the codacy review

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 1]
```diff
@@ -88,6 +91,28 @@ protected void onCreate(Bundle savedInstanceState) {
             Views.hideKeyboard(this, this.getCurrentFocus());
             saveChanges();
         });
+
+
+        ActivityCompat.requestPermissions(EditProfileActivity.this,
+                new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},1);
+        }
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Poor code formatting. Please check Java code style guidelines

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 2]
```diff
@@ -88,6 +91,28 @@ protected void onCreate(Bundle savedInstanceState) {
             Views.hideKeyboard(this, this.getCurrentFocus());
             saveChanges();
         });
+
+
+        ActivityCompat.requestPermissions(EditProfileActivity.this,
+                new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},1);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: What is 1?

Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Array should be used as constant

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 3]
```diff
@@ -88,6 +91,28 @@ protected void onCreate(Bundle savedInstanceState) {
...
+        }
+
+    @Override
+    public void onRequestPermissionsResult(int requestCode, String permissions[], int[] grantResults) {
+        switch (requestCode) {
+            case 1: {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: What is 1?

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 4]
```diff
@@ -88,6 +91,28 @@ protected void onCreate(Bundle savedInstanceState) {
...
         });
+
+
+        ActivityCompat.requestPermissions(EditProfileActivity.this,
+                new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},1);
+        }
+
+    @Override
+    public void onRequestPermissionsResult(int requestCode, String permissions[], int[] grantResults) {
+        switch (requestCode) {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Use of switch with only 1 case

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 5]
```diff
@@ -88,6 +91,28 @@ protected void onCreate(Bundle savedInstanceState) {
...
+            case 1: {
+                if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
```
[the remark this answers is not in the document]
Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Should you do nothing if permission is granted?

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

**Comment by dreadpool2** [comment]
@iamareebjamal I apologise for the silly error!. PR updated

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java (hunk 2 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Its actually the request code of the permission

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 6]
```diff
@@ -58,6 +61,8 @@
     private TextInputEditText lastNameInput;
 
     private User user;
+    private String [] READ_STORAGE = new String[]{Manifest.permission.READ_EXTERNAL_STORAGE} ;
+    private int REQUEST_CODE = 1;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Make both static and final

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 7]
```diff
@@ -58,6 +61,8 @@
     private TextInputEditText lastNameInput;
 
     private User user;
+    private String [] READ_STORAGE = new String[]{Manifest.permission.READ_EXTERNAL_STORAGE} ;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Space before ;

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 8]
```diff
@@ -88,6 +93,17 @@ protected void onCreate(Bundle savedInstanceState) {
...
             saveChanges();
         });
+
+        ActivityCompat.requestPermissions(EditProfileActivity.this, READ_STORAGE, REQUEST_CODE);
+    }
+
+    @Override
+    public void onRequestPermissionsResult(int requestCode, String permissions[], int[] grantResults) {
+                if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
+                    Toast.makeText(EditProfileActivity.this, "Access Successfull", Toast.LENGTH_SHORT).show();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Why we are showing toast to the user, instead respective action should be taken for which the permission was sought. Also, the spelling of `successful` is wrong

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 9]
```diff
@@ -88,6 +93,17 @@ protected void onCreate(Bundle savedInstanceState) {
...
+                } else {
+                    Toast.makeText(EditProfileActivity.this, "Permission denied to access your External storage", Toast.LENGTH_SHORT).show();
+                }
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Wrong indentation

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 10]
```diff
@@ -88,6 +93,17 @@ protected void onCreate(Bundle savedInstanceState) {
             Views.hideKeyboard(this, this.getCurrentFocus());
             saveChanges();
         });
+
+        ActivityCompat.requestPermissions(EditProfileActivity.this, READ_STORAGE, REQUEST_CODE);
+    }
+
+    @Override
+    public void onRequestPermissionsResult(int requestCode, String permissions[], int[] grantResults) {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: String permissions[] is not according to guidelines

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: grantResults -> granted

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java (hunk 8 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: @iamareebjamal Actually, if the permission is granted the settings is automatically changed in the phone and thus no special action is required, so I thought a Toast message will thus notify the user

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: @iamareebjamal Should I just remove the extra method involving the Toast messages? method `onRequestPermissionsResult`

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: We should be taking the action when permission is granted. Not just silently passing it

**Comment by dreadpool2** [comment]
@iamareebjamal I removed the method as it really was used to show the toast messages. Updated the PR

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java (hunk 8 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: What type of action are you referring to?

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: @iamareebjamal Like storage permissions are granted just after checking the dialog right? Is there a requirement of an other action?

**Comment by dreadpool2** [comment]
@iamareebjamal PR updated

**Comment by dreadpool2** [comment]
@iamareebjamal Is there a requirement to change the PR ?

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 11]
```diff
@@ -88,6 +92,8 @@ protected void onCreate(Bundle savedInstanceState) {
             Views.hideKeyboard(this, this.getCurrentFocus());
             saveChanges();
         });
+
+        ActivityCompat.requestPermissions(EditProfileActivity.this, READ_STORAGE, REQUEST_CODE);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Where is the permission response handled?

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java (hunk 11 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: @iamareebjamal Why do we need to handle the permission response ? Like we just need the app to allow access to external storage right ?

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: What if user declined? The app will crash as before. Then what's the point of this PR?

**Comment by dreadpool2** [comment]
@iamareebjamal PR updated

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 12]
```diff
@@ -82,7 +87,14 @@ protected void onCreate(Bundle savedInstanceState) {
             showUserData(user);
         });
 
-        avatar.setOnClickListener(v -> showFileChooser());
+
```
Comment (simarsingh24) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: remove this line feed

**Review by iamareebjamal — CHANGES_REQUESTED** [review]
Unfortunately, still no callback to handle the permission response is added

**Comment by iamareebjamal** [comment]
@dreadpool2 How does finalizing the PR mean closing it? A simple callback is to be implemented to handle the permission grant/deny. The user is to be notified of the action and the action is to be proceeded with or the activity has to close respectively

**Comment by dreadpool2** [comment]
@iamareebjamal Apologies :sweat_smile: , I thought that all PRs needed to be closed by now. I will work on it straightahead

**Comment by dreadpool2** [comment]
@iamareebjamal The current state of the app is that whenever the user is clicking on the profile pic , a dialog for requesting external storage permission is fired. Until and unless the user grants permission the dialog will always be fired.

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 13]
```diff
@@ -82,7 +87,14 @@ protected void onCreate(Bundle savedInstanceState) {
...
+        avatar.setOnClickListener(v -> {
+            if(checkReadExternalPermission()) {
+                showFileChooser();
```
Comment (dreadpool2) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Here there is a check where the app checks whether external storage permission is granted or not. So when the user clicks the profile pic and denies permission file chooser is not fired.

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: So to update the pic the user needs to grant the app external permission. Do correct me if I am not able to get your point at all !

**Comment by simarsingh24** [comment]
@dreadpool2 you are not using a callback when permission is granted

**Comment by simarsingh24** [comment]
https://developer.android.com/training/permissions/requesting#java
read this
screen shot 2018-06-01 at 10 17 12 am

**Comment by dreadpool2** [comment]
@simarsingh24 Thanks a lot. Got the point :+1:

**Comment by dreadpool2** [comment]
@iamareebjamal @simarsingh24 Please review

**Comment by ghost** [comment]
Hi @dreadpool2!

It looks like one or more of your builds have failed.
I've added the relevant info below to save you some time.

- [Build 5513.1](https://travis-ci.org/fossasia/open-event-android/jobs/386502875) has `failed`

**Comment by simarsingh24** [comment]
check why build is failing

**Comment by dreadpool2** [comment]
Did the change :+1:

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 14]
```diff
@@ -82,7 +88,13 @@ protected void onCreate(Bundle savedInstanceState) {
             showUserData(user);
         });
 
-        avatar.setOnClickListener(v -> showFileChooser());
+        avatar.setOnClickListener(v -> {
+            if(!checkReadExternalPermission()) {
```
Comment (simarsingh24) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: instead of calling this function everytime keep a boolean to check if user has the permissions or not, update that boolean in the callback onRequestPermissionResult,
or lets wait for @iamareebjamal  for his views on this

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Okay

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Exactly, and take the reactive approach

**Comment by dreadpool2** [comment]
@iamareebjamal Please review :+1:

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 15]
```diff
@@ -82,7 +98,21 @@ protected void onCreate(Bundle savedInstanceState) {
             showUserData(user);
         });
 
-        avatar.setOnClickListener(v -> showFileChooser());
+        Observable<Boolean> picObserver = Observable.just(checkReadExternalPermission());
+        picObserver.subscribeOn(Schedulers.io())
+                .observeOn(AndroidSchedulers.mainThread())
+                .subscribe(picBool -> {
+                    if (picBool) {
```
Comment (simarsingh24) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: checking picBool to be true to set permission granted true makes no sense
also please use standard naming conventions

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 16]
```diff
@@ -82,7 +98,21 @@ protected void onCreate(Bundle savedInstanceState) {
...
+                        permissionGranted = true;
+                    } else {
+                        ActivityCompat.requestPermissions(EditProfileActivity.this, READ_STORAGE, REQUEST_CODE);
+                    }
+                });
```
Comment (simarsingh24) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: not sure this is a good way to do it, let the mentor weigh in

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 17]
```diff
@@ -98,13 +93,13 @@ protected void onCreate(Bundle savedInstanceState) {
             showUserData(user);
         });
 
-        Observable<Boolean> picObserver = Observable.just(checkReadExternalPermission());
-        picObserver.subscribeOn(Schedulers.io())
+        Observable<Boolean> picRequestObserver = Observable.just(checkReadExternalPermission());
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: This has no use of being wrapped in an obserable

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 18]
```diff
@@ -82,7 +93,19 @@ protected void onCreate(Bundle savedInstanceState) {
...
+        picRequestObserver.subscribeOn(Schedulers.io())
+                   .observeOn(AndroidSchedulers.mainThread());
+
+        avatar.setOnClickListener(v -> {
+            picRequestObserver.subscribe(picRequestBoolean -> {
+                    if (picRequestBoolean) {
+                        showFileChooser();
+                    } else {
+                        ActivityCompat.requestPermissions(EditProfileActivity.this, READ_STORAGE, REQUEST_CODE);
```
Comment (dreadpool2) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: @iamareebjamal Should I wrap this with an observable?

**Comment by dreadpool2** [comment]
@iamareebjamal Please Review

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 19]
```diff
@@ -82,7 +94,18 @@ protected void onCreate(Bundle savedInstanceState) {
             showUserData(user);
         });
 
-        avatar.setOnClickListener(v -> showFileChooser());
+        permissionGranted = checkReadExternalPermission();
+        Observable<Object> picRequestObserver = Observable.create(emitter -> ActivityCompat.requestPermissions(EditProfileActivity.this, READ_STORAGE, REQUEST_CODE));
+        picRequestObserver.subscribeOn(Schedulers.io())
+                .observeOn(AndroidSchedulers.mainThread());
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: There is simply no use of Observable here at all

How does wrapping in observer help? Please follow up with a discussion, not a commit or else we'll be stuck in this loop for days on end

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java (hunk 19 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Yeah. I too thought simply that it wont be of any use. I am not really able to get the part where we should use reactive

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: @iamareebjamal Where exactly do we need reactive?

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: See the pic @simarsingh24 posted above, you need to react to the permission grant or failure correctly

Read the documentation on how to handle the permission access

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: https://user-images.githubusercontent.com/16715499/40821518-149e4baa-6585-11e8-819b-d0cbc55d4029.png

Also, follow up with what you are going to do so that we can understand and approve. Committing another solution after hours to be requested again is not a good way to iterate on solutions. We should have been on same page since starting the issue.

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 20]
```diff
@@ -272,4 +288,22 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+
+    @Override
+    public void onRequestPermissionsResult(int requestCode, @NonNull String permissions[], @NonNull int[] grantResults) {
+        if (requestCode == REQUEST_CODE) {
+            if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
+                permissionGranted = true;
+                showFileChooser();
+            } else {
+                finish();
+            }
```
Comment (dreadpool2) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: @iamareebjamal Added the callback :+1:

File: android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java [hunk 21]
```diff
@@ -272,4 +288,22 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+    }
+
+    @Override
+    public void onRequestPermissionsResult(int requestCode, @NonNull String permissions[], @NonNull int[] grantResults) {
+        if (requestCode == REQUEST_CODE) {
+            if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
+                permissionGranted = true;
+                showFileChooser();
+            } else {
+                finish();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/auth/profile/EditProfileActivity.java]: Excellent! Just add a Toast here and we are done

**Comment by dreadpool2** [comment]
@iamareebjamal Added the Toast messages :+1:

**Review by iamareebjamal — APPROVED** [review]
