### PR TITLE
fix : made ViewModel for SearchActivity (fixes #2051)

### LINKED ISSUE #2051: Create ViewModel for SearchActivity
**Actual Behaviour**

There is no ViewModel for the SearchActivity

**Expected Behaviour**

There should be one.

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

NA

**Other information**

Parent issue #2015

### PR DESCRIPTION
**Pull request by dreadpool2**
Fixes #2051

Changes: ViewModel for SearchActivity has been created.

### CODE REVIEW

**Comment by dreadpool2** [comment]
@srv-twry @iamareebjamal  please review !

**Comment by dr0pdb** [comment]
@dreadpool2 Please resolve merge conflicts first.

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 1]
```diff
@@ -57,25 +62,34 @@ protected void onCreate(Bundle savedInstanceState) {
...
-        handleVisibility();
-
-        globalSearchAdapter = new GlobalSearchAdapter(results, this);
-        searchRecyclerView.setAdapter(globalSearchAdapter);
-        searchRecyclerView.addItemDecoration(new DividerItemDecoration(this, DividerItemDecoration.VERTICAL));
-        searchRecyclerView.setLayoutManager(new LinearLayoutManager(this));
+        setUpRecyclerView();
 
         if (savedInstanceState != null && savedInstanceState.getString(SEARCH) != null) {
             searchText = savedInstanceState.getString(SEARCH);
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Remove this now, you don't need to save the searchText in the ```saveInstanceState```. You can save it inside the ViewModel which will outlast the life of this Activity.

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 2]
```diff
@@ -57,25 +62,34 @@ protected void onCreate(Bundle savedInstanceState) {
...
+             });
+        }
+        handleVisibility();
+
     }
 
     @Override
     protected int getLayoutResource() {
-        return R.layout.activity_search;
+       return R.layout.activity_search;
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Indentation is off, infact don't touch the part of the code which your issue isn't associated with.

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+import io.realm.RealmResults;
+
+/**
+ * Created by sanyog on 1/1/18.
+ */
+
+public class SearchActivityViewModel extends ViewModel {
+
+
+    private MutableLiveData<List<Object>> searchResults;
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: Don't add unnecessary lines.

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+        return searchText;
+    }
+
+    public void setSearchText(String searchText) {
+        this.searchText = searchText;
+    }
+
+    @Override
+    protected void onCleared() {
+        super.onCleared();
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: You should dispose all the changeListeners if you have any, otherwise this method is redundant since it is only calling it's super class.

**Review by dr0pdb — CHANGES_REQUESTED** [review]
Apart from the inline comments that i have made, i would recommend you to revert all the unnecessary changes that you have made, for eg: i don't think you need to make changes in the layout for this issue.
Please focus on the issue only, if you want to make other changes , then please create an issue for it and send us a PR :smile:

**Comment by dreadpool2** [comment]
@srv-twry Sir, Thanks for all the suggested changes  :smile:

**Comment by dr0pdb** [comment]
@dreadpool2 Please don't call me sir :)

**Comment by dreadpool2** [comment]
@srv-twry Is the PR alright for review or should I change anything else ?

File: android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java [hunk 5]
```diff
@@ -357,6 +357,10 @@ public Session getSessionSync(int sessionId) {
         return realm.where(Session.class).equalTo("id", sessionId).findFirst();
     }
 
+    public RealmResults<Session> getSessions() {
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java]: Can you explain why you needed to add this ? I mean how was the session fetched before implementing the ViewModel ?

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+
+import java.util.ArrayList;
+import java.util.List;
+
+import io.realm.RealmResults;
+
+/**
+ * Created by sanyog on 1/1/18.
+ */
+
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: Please delete this template

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+            int c = realmResults_speaker.size();
+            realmResults_microloc = realmRepo.getLocations();
+            objectList.add(realmResults_microloc);
+
+            int d = realmResults_track.size();
+            if(a+b+c+d == 0){
+                return null;
+            }
+            else {
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: According to standard guidelines, ```else``` should start from the end of the ```if``` block. Don't add a new line.

File: android/app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java [hunk 8]
```diff
@@ -77,10 +77,9 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle sa
         //set up view model
         locationsFragmentViewModel = ViewModelProviders.of(this).get(LocationsFragmentViewModel.class);
         searchText = locationsFragmentViewModel.getSearchText();
-        locationsFragmentViewModel.getLocations().observe(LocationsFragment.this, microlocations ->  {
+        locationsFragmentViewModel.getLocations().observe(LocationsFragment.this, microlocations -> {
                 locations.clear();
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java]: I don't understand why you had to edit ```LocationsFragment``` if you are creating ViewModel for ```SearchActivity```. Was changing this file absolutely necessary ?

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java [hunk 9]
```diff
@@ -0,0 +1,74 @@
...
+            realmResults_speaker = realmRepo.getSpeakers();
+            objectList.add(realmResults_speaker);
+
+            int c = realmResults_speaker.size();
+            realmResults_microloc = realmRepo.getLocations();
+            objectList.add(realmResults_microloc);
+
+            int d = realmResults_track.size();
+            if(a+b+c+d == 0){
+                return null;
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: You're returning ```null```, wouldn't that lead to null pointer exception ?

**Review by dr0pdb — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java (hunk 5 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java]: Like actually I wanted to fetch all microlocations , speakers , tracks and sessions so I created a method for Sessions and Speakers differently as they were not present before (I sorted them according to their title and name respectively). Then I added all of them to an arraylist of object type.

File: android/app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java (hunk 8 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/fragments/LocationsFragment.java]: This was a silly error 😅

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java (hunk 6 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: Yeah Sure

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java (hunk 9 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: Actually on the other side, the Search Activity side, I have implemented a conditional which would disregard the null statements.

File: android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java (hunk 5 above)
Comment (dr0pdb) [reply android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java]: Actually my question is if it wasn't present before , then how was it implemented before ? I mean it was working before, it's just a refactor from View to ViewModel. Ideally there shouldn't be any changes to the repository layer.

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 10]
```diff
@@ -57,20 +62,25 @@ protected void onCreate(Bundle savedInstanceState) {
...
-        }
+        setUpRecyclerView();
 
         if (Intent.ACTION_SEARCH.equals(getIntent().getAction())) {
             handleIntent(getIntent());
         }
+
+        searchViewModel = ViewModelProviders.of(this).get(SearchActivityViewModel.class);
+        searchText = searchViewModel.getSearchText();
+        if(searchViewModel.getSearchResults()!=null) {
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: It's not the right way to do it. Infact even after doing this null check, the ```searches``` list could be null. The LiveData is just a wrapper around it. I would suggest you remove this null check, and instead of returning ```null```, return an empty list from the ViewModel

**Review by dr0pdb — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java (hunk 9 above)
Comment (dr0pdb) [reply android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: I have added another comment. Please check it.

File: android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java (hunk 5 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java]: Actually Realm.where(Speaker.class) is used to find the full list. There wasn't a method before like it did in the case of microlocations and tracks 😅

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java (hunk 10 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Oh, yeah that could be a problem. Sure I will change it 👍

File: android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java (hunk 5 above)
Comment (dr0pdb) [reply android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java]: Yes, then please don't change the implementation. Implement it the way it was done before. Incase you want to change the implementation, create an issue for it.

Comment (dr0pdb) [reply android/app/src/main/java/org/fossasia/openevent/dbutils/RealmDataRepository.java]: Please find the methods like ```addResultsFromLocations``` to get the idea of how to fetch only ```Locations``` from the database. I think you should first go through and understand it.

**Comment by dreadpool2** [comment]
@srv-twry After I went through the repository carefully I realized I had missed two methods corresponding to both speaker and session items :sweat_smile:

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 11]
```diff
@@ -123,11 +138,20 @@ protected void onNewIntent(Intent intent) {
     }
 
     public void handleIntent(Intent intent) {
+
         final String query = intent.getStringExtra(SearchManager.QUERY);
         searchQuery(query);
     }
+    @Override
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Add empty line above

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 12]
```diff
@@ -227,6 +245,7 @@ public void handleVisibility() {
         if (results.size() == 0) {
             noResultsView.setVisibility(View.VISIBLE);
             searchRecyclerView.setVisibility(View.INVISIBLE);
+
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Please don't add unnecessary empty lines

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java [hunk 13]
```diff
@@ -0,0 +1,71 @@
...
+    private MutableLiveData<List<Object>> searchResults;
+    private RealmDataRepository realmRepo;
+    private String searchText = "";
+
+    public SearchActivityViewModel() {
+        realmRepo = RealmDataRepository.getDefaultInstance();
+    }
+
+    public LiveData<List<Object>> getSearchResults() {
+        RealmResults<Microlocation> realmResults_microloc;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: Please use Java camel case notation to name variables

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java [hunk 14]
```diff
@@ -0,0 +1,71 @@
...
+            realmResults_microloc = realmRepo.getLocations();
+            objectList.add(realmResults_microloc);
+
+            int d = realmResults_track.size();
+            if(a+b+c+d == 0){
+                return new MutableLiveData<>();
+            }else{
+                 searchResults.setValue(objectList);
+            }
+        }
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: The naming is very poor here. Please change it to meaningful names rather than using a b c d e

There's no clue what the variables are used for.

Also, please see that the if cases are correctly used. You are doing everything in null check branch, whereas if the searchResults is not null, none of this will be called and what you will set as a value of objectList will be empty. Null check branch should only be used to instantiate the searchResults object and nothing else

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: Also, in case of the sum being 0, you are sending a new MutableLiveData which is not needed. You should just set the empty value to the existing LiveData

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java (hunk 14 above)
Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: Also please add spaces where necessary, like around the `else`

**Comment by dreadpool2** [comment]
@iamareebjamal I have done the requested changes. There was no need of an else statement in the results summation part actually :sweat_smile:

**Review by dr0pdb — CHANGES_REQUESTED** [review]
I suggest you please have a look at methods like ```addResultFromSessions``` etc. You need to move this logic to ```ViewModel```. Database interaction isn't supposed to be done inside the Activity.

**Comment by dreadpool2** [comment]
@srv-twry Somehow I am not able to receive the results from the viewmodel. It is returning empty even after a search query being set. Am I missing something?

**Comment by dr0pdb** [comment]
It's difficult to say what could be wrong. What i would do in this situation is to check how other ViewModel's have been implemented and how data is fetched from these ViewModel's by other Fragment/Activity.

**Comment by dreadpool2** [comment]
@srv-twry Actually the thing here is that the data is not fully loaded to be filtered like in other activities or fragments like SpeakerListFragment or LocationFragment. That's why its a little bit different than others :sweat_smile:

**Comment by dr0pdb** [comment]
@dreadpool2 In the ViewModel that you have implemented, i would suggest you try removing the non-empty check on line 47 i.e. ```!searchText.equals("")```. I don't understand the need of this check, so can you explain why it's needed ?

**Comment by dreadpool2** [comment]
@srv-twry I actually did remove it after a brief check as it was indeed not necessary!

**Comment by dreadpool2** [comment]
@srv-twry Actually I imported the addResultFromSessions ..etc methods from SearchActivity to the ViewModel, thus the check was redundant.

**Comment by dr0pdb** [comment]
I guess probably @iamareebjamal could help you.

**Comment by dreadpool2** [comment]
@iamareebjamal Even after connecting both the viewmodel and the SearchActivity successfully, an empty list is being returned. How do I overcome this issue? :sweat:

**Comment by dreadpool2** [comment]
@iamareebjamal Is the PR alright?

**Comment by iamareebjamal** [comment]
@dreadpool2 Sorry I did not get the time to inspect the code. Are you facing any difficulty in completing the goal of the issue or is it complete?

**Comment by dreadpool2** [comment]
@iamareebjamal Sir actually I want to know whether the pushed code is correct as I have a doubt whether there should be any database interaction in SearchActivity.

**Comment by dreadpool2** [comment]
@srv-twry Sorry to bother you again :sweat_smile: .I actually managed to separate the database interaction from the activity. But I am facing problem in the `OnQueryTextChange` method of SearchView. The frustrating thing which is happening is that when I start typing my query, like If I type "a",the results are updated below, but then if I go on typing "ab", the query results of "ab" are appended below the results of "a". Like I am not at all able to clear the previous results present in the RecyclerView. I have tried all the `clear` methods but still the problem occurs.

**Comment by dreadpool2** [comment]
@srv-twry  I have solved it :sweat_smile:

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 15]
```diff
@@ -100,16 +88,27 @@ public boolean onCreateOptionsMenu(Menu menu) {
 
     @Override
     public boolean onQueryTextChange(String query) {
-        if (query != null) {
-            searchQuery(query);
+        String query1 = query.toLowerCase(Locale.getDefault());
+        String wildcardQuery = String.format("*%s*", query1);
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Do all these things in the ViewModel only.

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 16]
```diff
@@ -100,16 +88,27 @@ public boolean onCreateOptionsMenu(Menu menu) {
...
+        searchViewModel.setSearchText(wildcardQuery);
+
+        if (!query.equals("")) {
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Can you explain the use of this non-empty check ?

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 17]
```diff
@@ -127,25 +126,27 @@ public void handleIntent(Intent intent) {
         searchQuery(query);
     }
 
+    @Override
+    public void onSaveInstanceState(Bundle bundle) {
+        if (searchView != null && searchViewModel != null) {
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: No need for a null check on searchView if you aren't using it anywhere.

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 18]
```diff
@@ -127,25 +126,27 @@ public void handleIntent(Intent intent) {
...
+            searchViewModel.setSearchText(searchText);
+        }
+        super.onSaveInstanceState(bundle);
+    }
+
     private void searchQuery(String constraint) {
         results.clear();
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Add this clear method inside the getSearchResults call.

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 19]
```diff
@@ -127,25 +126,27 @@ public void handleIntent(Intent intent) {
...
+        globalSearchAdapter.clear();
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Please explain the significance of this line

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java [hunk 20]
```diff
@@ -0,0 +1,111 @@
...
+
+    public LiveData<List<Object>> getSearchResults() {
+        objectList.clear();
+        MutableLiveData<List<Object>> searchResults = new MutableLiveData<>();
+
+        addResultFromSessions(searchText);
+        addResultsFromLocations(searchText);
+        addResultsFromSpeakers(searchText);
+        addResultsFromTracks(searchText);
+
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: Don't add unnecessary lines.

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java [hunk 21]
```diff
@@ -0,0 +1,111 @@
...
+    private List<Object> objectList = new ArrayList<>();
+    private Realm realm;
+
+    public SearchActivityViewModel() {
+        realm = Realm.getDefaultInstance();
+    }
+
+    public LiveData<List<Object>> getSearchResults() {
+        objectList.clear();
+        MutableLiveData<List<Object>> searchResults = new MutableLiveData<>();
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: You're creating a LiveData everytime the method is called. Make it global and do it only once.

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 22]
```diff
@@ -100,16 +88,27 @@ public boolean onCreateOptionsMenu(Menu menu) {
 
     @Override
     public boolean onQueryTextChange(String query) {
-        if (query != null) {
-            searchQuery(query);
+        String query1 = query.toLowerCase(Locale.getDefault());
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: No need for this temporary varialble, why not just add it inside the String.format call

**Review by dr0pdb — CHANGES_REQUESTED** [review]
I couldn't find where you're fetching the searchQuery text from the ViewModel inside the Activity.

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 23]
```diff
@@ -127,25 +126,27 @@ public void handleIntent(Intent intent) {
...
-    @Override
-    protected void onSaveInstanceState(Bundle outState) {
-        if (searchView != null) {
-            outState.putString(SEARCH, searchText);
+            searchViewModel.getSearchResults().observe(SearchActivity.this, searches -> {
+                results.add(searches);
+                globalSearchAdapter.setCopyOfSearches(searches);
+                globalSearchAdapter.notifyDataSetChanged();
+                handleVisibility();
+            });
```
Comment (dreadpool2) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: @srv-twry I am keeping all the results in the viewmodel. I am fetching those in the above `searchQuery` method

Comment (dr0pdb) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: I asked about the searchText variable that you've stored in the ViewModel, where are you using the ```getSearchText``` method of the ViewModel inside the Activity ?

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java (hunk 22 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: @srv-twry Sure

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java (hunk 20 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: @srv-twry I actually grouped all the four methods together :sweat_smile:

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java (hunk 23 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: @srv-twry Oh,I completely forgot to invoke the function in the `searchQuery` method.

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java (hunk 20 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: @srv-twry Is it correct to do so ?

Comment (dr0pdb) [reply android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: No need for that, it's still clear. Remove the empty lines

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java (hunk 16 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: @srv-twry I did this as if the query is empty then the `handleVisibility` function will be invoked

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: @srv-twry Do I proceed with this ?

**Comment by dreadpool2** [comment]
@srv-twry @iamareebjamal Please review

**Comment by dr0pdb** [comment]
Please resolve conflicts.

**Comment by dreadpool2** [comment]
@srv-twry Resolved the conflicts 😅

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java [hunk 24]
```diff
@@ -0,0 +1,111 @@
...
+        filteredSessions.addChangeListener(sessions -> {
+            if (sessions.size() > 0) {
+                objectList.add("Sessions");
+            }
+            objectList.addAll(sessions);
+            Timber.d("Filtering done total results %d", sessions.size());
+        });
+    }
+
+    public void onDestroy(){
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: This should be overriden method, `onCleared`

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java (hunk 24 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: @iamareebjamal Done the change!

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 25]
```diff
@@ -127,25 +121,28 @@ public void handleIntent(Intent intent) {
...
 
-    @Override
-    protected void onSaveInstanceState(Bundle outState) {
-        if (searchView != null) {
-            outState.putString(SEARCH, searchText);
+    private void searchQuery(String constraint) {
+        searchViewModel.setSearchText(constraint);
+        searchText = searchViewModel.getSearchText();
+
+        if (!TextUtils.isEmpty(constraint)) {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: The ifs and above two lines can be inside ViewModel, there is no need to just update the search text this way

**Review by iamareebjamal — COMMENTED** [review]
One last bit of change

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java (hunk 25 above)
Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Also resolve conflicts

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: @iamareebjamal I am setting the search text in the ViewModel as constraint. Why should it be inside the ViewModel ?

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: @iamareebjamal And in the next line I am receiving the search text from the ViewModel and as it is a global variable we are using this search text in the `onSaveInstanceState` method, kind of storing it.

**Comment by dreadpool2** [comment]
@srv-twry Then is there any application of the `getSearchText` method in the activity ?. Should I just remove it from both the ViewModel and SearchActivity ?

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java (hunk 25 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: @iamareebjamal Like I wont receive any results while observing the model until and unless the 'constraint' query is stored in the ViewModel itself !.

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: You can pass the searchText in the method parameter and add the condition in ViewModel instead of activity. Setting the search text and then getting it is not appropriate. I never said about not saving it in the fragment.

About the search being done through the text, that's why I'm saying, when you pass it in the method then set it in the viewmodel itself -> Why is there a need of explicit setting of search text in view model, when it can be done from inside the viewmodel when it is received as an argument

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: @iamareebjamal Is the `getSearchText` method redundant then?

Comment (dr0pdb) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: @dreadpool2 It's not redundant. You have to use it when the Activity is getting destroyed.

**Edit** - You can delete it since everytime the search text changes we are updating the string in the ViewModel also.

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: @iamareebjamal I beg your pardon but I didn't understand the second part of your answer :sweat_smile: , like how the search text is obtained inside the viewmodel.

**Comment by dreadpool2** [comment]
@srv-twry Why should I keep the search text when the activity itself gets destroyed?

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java (hunk 25 above)
Comment (dr0pdb) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: @dreadpool2 What he means to say is, everytime you want to filter, just pass in the string as an argument to the filter method and update the string inside the ViewModel in that method only. No need for the public method ```setSearchText()```

**Comment by dr0pdb** [comment]
@dreadpool2 Yes, i have edited my above comments. You can delete the setSearchText method.

**Comment by dr0pdb** [comment]
> Then is there any application of the getSearchText method in the activity ?. Should I just remove it from both the ViewModel and SearchActivity ?

Yes, it is used in case of screen rotation. If the screen is rotated the activity will be destroyed but the ViewModel will be alive hence when the activity is recreated, you can fetch the searchText that you had saved in the ViewModel.

**Comment by dreadpool2** [comment]
@srv-twry I have pushed the code. I have done the requested changes.

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 26]
```diff
@@ -159,68 +148,7 @@ public void onDestroy() {
...
-        filteredSessions.addChangeListener(sessions -> {
-            if (sessions.size() > 0) {
-                results.add("Sessions");
-            }
-            results.addAll(filteredSessions);
-            globalSearchAdapter.notifyDataSetChanged();
-            Timber.d("Filtering done total results %d", sessions.size());
-            handleVisibility();
-        });
+        searchText = searchViewModel.getSearchText();
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Why are you getting the searchText in the ```onDestroy``` ?

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 27]
```diff
@@ -57,20 +52,12 @@ protected void onCreate(Bundle savedInstanceState) {
...
-        if (savedInstanceState != null && savedInstanceState.getString(SEARCH) != null) {
-            searchText = savedInstanceState.getString(SEARCH);
-        }
+        setUpRecyclerView();
 
         if (Intent.ACTION_SEARCH.equals(getIntent().getAction())) {
             handleIntent(getIntent());
         }
+        searchViewModel = ViewModelProviders.of(this).get(SearchActivityViewModel.class);
     }
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Also fetch the searchText from the ViewModel after setting the ViewModel

**Review by dr0pdb — CHANGES_REQUESTED** [review]

**Comment by dr0pdb** [comment]
@dreadpool2 It seems like you're unable to understand the workflow. Here it is in an abstract way:

1. Activity created for the first time
2. ViewModel created with searchText = ""
3. Now you fetch the data. Now the user add a searchQuery.
4. You pass in the searchQuery to the filter method in the ViewModel and update the searchText variable.
5. You return the filtered results.
6. The user rotates the device, the activity is recreated. Now the user will expect you to start again with the filtered data not the original unfiltered data.
7. So you fetch the searchText variable from the ViewModel which would survive the configuration changes. (Replacing the functionality of the onSaveInstanceState method).
8. You fetch the data for the recreated Activity using that searchText.

If you have any problem understanding this, please ask.

**Comment by dreadpool2** [comment]
@srv-twry I did the changes in a hurry. Please ignore my silly errors :sweat:

**Comment by dreadpool2** [comment]
@srv-twry Thanks for such a long comment, it's crystal clear now :smile: . Though I believe I might have finally pushed the right code :sweat_smile:

**Comment by dr0pdb** [comment]
@dreadpool2 Please resolve conflicts also.

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 28]
```diff
@@ -127,25 +122,23 @@ public void handleIntent(Intent intent) {
...
-        if (!TextUtils.isEmpty(constraint)) {
-            String query = constraint.toLowerCase(Locale.getDefault());
-            String wildcardQuery = String.format("*%s*", query);
-            addResultsFromTracks(wildcardQuery);
-            addResultFromSessions(wildcardQuery);
-            addResultsFromSpeakers(wildcardQuery);
-            addResultsFromLocations(wildcardQuery);
+    @Override
+    public void onSaveInstanceState(Bundle bundle) {
+        if(searchViewModel!=null){
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Add space before and after ```!=```

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 29]
```diff
@@ -127,25 +122,23 @@ public void handleIntent(Intent intent) {
...
+            searchView.setQuery(searchText,true);
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Add space after comma

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 30]
```diff
@@ -100,7 +88,7 @@ public boolean onCreateOptionsMenu(Menu menu) {
 
     @Override
     public boolean onQueryTextChange(String query) {
-        if (query != null) {
+        if (!TextUtils.isEmpty(query)) {
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Can you please explain the use of this check? I mean we are already checking that in the line 37 of the ViewModel. Now if that is empty , then we will get an empty list from the ViewModel and we are already clearing the results List and handeling Visibility in ```searchQuery``` method in the Activity.
I know you haven't written this code but i feel this is redundant and should be removed to keep the code simpler.
@iamareebjamal What do you think ?

**Review by dr0pdb — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java (hunk 30 above)
Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Yes, that was what I was saying, it should be inside ViewModel, and if it there, it shouldn't be here anyway

**Comment by dreadpool2** [comment]
@iamareebjamal Did the changes

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 31]
```diff
@@ -134,103 +123,37 @@ public void handleIntent(Intent intent) {
...
-            String query = constraint.toLowerCase(Locale.getDefault());
-            String wildcardQuery = String.format("*%s*", query);
-            addResultsFromTracks(wildcardQuery);
-            addResultFromSessions(wildcardQuery);
-            addResultsFromSpeakers(wildcardQuery);
-            addResultsFromLocations(wildcardQuery);
+    @Override
+    public void onSaveInstanceState(Bundle bundle) {
+        if(searchViewModel != null){
+            searchView.setQuery(searchText, true);
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Can you explain what you're trying to do here ?

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 32]
```diff
@@ -134,103 +123,37 @@ public void handleIntent(Intent intent) {
...
-        super.onSaveInstanceState(outState);
+    private void searchQuery(String constraint) {
+        searchViewModel.getSearchResults(constraint).observe(SearchActivity.this, searches -> {
+            results.clear();
+            results.add(searches);
+            globalSearchAdapter.setCopyOfSearches(searches);
+            globalSearchAdapter.notifyDataSetChanged();
+            handleVisibility();
+        });
+        handleVisibility();
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: No need to handle Visibility twice

**Review by dr0pdb — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java (hunk 31 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: @srv-twry As I dont have a `setSearchText` method in viewmodel to save the text there after configuration change, I set the text in searchView to searchText in the `onSaveInstanceState` method

Comment (dr0pdb) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Well , you could have created the method in case you needed them. Although here in my opinion you don't need to save it anywhere. Everytime you change the searchText in the search bar, the ViewModel is queried with that query and the searchText is saved in the ViewModel. So that means, the ViewModel always has the most updated searchText saved. No need to set it again.

**Comment by iamareebjamal** [comment]
Please resolve conflicts

**Comment by dreadpool2** [comment]
@iamareebjamal Resolved the conflicts 😅

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 33]
```diff
@@ -127,102 +118,32 @@ public void handleIntent(Intent intent) {
...
-        if (!TextUtils.isEmpty(constraint)) {
-            String query = constraint.toLowerCase(Locale.getDefault());
-            String wildcardQuery = String.format("*%s*", query);
-            addResultsFromTracks(wildcardQuery);
-            addResultFromSessions(wildcardQuery);
-            addResultsFromSpeakers(wildcardQuery);
-            addResultsFromLocations(wildcardQuery);
-        }
+    @Override
+    public void onSaveInstanceState(Bundle bundle) {
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Please delete this method now. Since the only thing you're doing is calling super, there is no need for this method.

**Review by dr0pdb — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java (hunk 33 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: @srv-twry Okay

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: @srv-twry But there can be future uses of this method right?

Comment (dr0pdb) [reply android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: This is an overridden method, which if not called explicitly for the SearchActivity will automatically be called for the super class. In case there are future requirements , one can easily create it again.

It is mainly used to save states, when orientation changes. Now that we have ViewModels which survive orientation changes, i don't think we will need it. In case we need it , we will create it.

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 34]
```diff
@@ -107,16 +95,18 @@ public boolean onCreateOptionsMenu(Menu menu) {
...
     public boolean onQueryTextChange(String query) {
-        if (!TextUtils.isEmpty(query)) {
-            searchQuery(query);
-            searchText = query;
-        } else {
-            results.clear();
-            handleVisibility();
-        }
+        searchQuery(query);
+        searchText = query;
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: There's no need for this line `searchText = query;`

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 35]
```diff
@@ -134,103 +124,33 @@ public void handleIntent(Intent intent) {
...
     }
 
     @Override
     public void onDestroy() {
         super.onDestroy();
         OpenEventApp.getEventBus().unregister(this);
-
         //Closing realm instance and detaching listeners to avoid memory leaks
         realm.close();
         realm.removeAllChangeListeners();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Why are there realm instances here now? Every database interaction should be moved to ViewModel

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java [hunk 36]
```diff
@@ -0,0 +1,112 @@
...
+
+    public SearchActivityViewModel() {
+        realm = Realm.getDefaultInstance();
+    }
+
+    public LiveData<List<Object>> getSearchResults(String search) {
+        objectList.clear();
+        String wildcardQuery = String.format("*%s*", search.toLowerCase(Locale.getDefault()));
+        searchText = search;
+        if (!TextUtils.isEmpty(wildcardQuery)) {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java]: If you look closely, wildcardQuery can NEVER be empty. It will always at least be ``**'`. So you need this check before formatting, not after

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

**Comment by dreadpool2** [comment]
@iamareebjamal Did the changes

File: android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java [hunk 37]
```diff
@@ -134,103 +121,30 @@ public void handleIntent(Intent intent) {
...
-        if (!TextUtils.isEmpty(constraint)) {
-            String query = constraint.toLowerCase(Locale.getDefault());
-            String wildcardQuery = String.format("*%s*", query);
-            addResultsFromTracks(wildcardQuery);
-            addResultFromSessions(wildcardQuery);
-            addResultsFromSpeakers(wildcardQuery);
-            addResultsFromLocations(wildcardQuery);
-        }
+    @Override
+    public void onSaveInstanceState(Bundle bundle) {
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/activities/SearchActivity.java]: Why is this method still here ?

**Review by dr0pdb — CHANGES_REQUESTED** [review]
Also fix the build

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java [hunk 38]
```diff
@@ -0,0 +1,112 @@
...
+
+    public SearchActivityViewModel() {
+        realm = Realm.getDefaultInstance();
+    }
+
+    public LiveData<List<Object>> getSearchResults(String search) {
+        objectList.clear();
+        String wildcardQuery = String.format("*%s*", search.toLowerCase(Locale.getDefault()));
+        searchText = search;
+        if (!TextUtils.isEmpty(search)) {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java:37]: As I reviewed previously `!TextUtils.isEmpty(search)` will always be true

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java (hunk 38 above)
Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java:37]: @iamareebjamal No! thats not the formatted string

Comment (dreadpool2) [reply android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java:37]: @iamareebjamal Its directly the `search` text. I have even checked it locally

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/viewmodels/SearchActivityViewModel.java:37]: Alright, my mistake

**Review by iamareebjamal — APPROVED** [review]
