### PR TITLE
fix: corrected the title of AboutFragment.java

### LINKED ISSUE #1734: Displaying Title in HomePage from event.json file
**Actual Behaviour**

Currently the app just shows the Fossasia title in the homepage.

**Expected Behaviour**

Displaying the title of the event from the event.json file.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/31

### PR DESCRIPTION
**Pull request by arp95**
Fixes #1734 

Changes:
Corrected the title of home page and renamed certain variables.

Screenshots for the change: 
-

@iamareebjamal @Shailesh351 @rohanagarwal94 @shreyasnbhat 
please review.

### CODE REVIEW

**Review by Shailesh351 — APPROVED** [review]

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java [hunk 1]
```diff
@@ -131,47 +130,43 @@ private void loadEvent(Event event) {
                 DateUtils.formatDateWithDefault(DateUtils.FORMAT_DATE_COMPLETE, event.getStartTime()),
                 DateUtils.formatDateWithDefault(DateUtils.FORMAT_DATE_COMPLETE, event.getEndTime()));
 
-        welcomeMessage.setText(getText(R.string.welcome_message));
```
Comment (rohanagarwal94) [inline android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java:134]: Please delete the corresponding string if its not required now.

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java [hunk 2]
```diff
@@ -131,47 +130,43 @@ private void loadEvent(Event event) {
...
-        Views.setHtml(organiser_description, event.getOrganizerDescription(), true);
-        Views.setHtml(event_description, event.getDescription(), true);
-        venue_details.setText(event.getLocationName());
-        event_timing.setText(date);
+        welcomeMessage.setText(event.getName());
```
Comment (rohanagarwal94) [inline android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: I think its better to maintain the original message with "Welcome to (event name)!" instead of just the event name.

**Review by rohanagarwal94 — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java (hunk 2 above)
Comment (arp95) [reply android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: sure! doing it.

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java [hunk 3]
```diff
@@ -131,47 +130,43 @@ private void loadEvent(Event event) {
                 DateUtils.formatDateWithDefault(DateUtils.FORMAT_DATE_COMPLETE, event.getStartTime()),
                 DateUtils.formatDateWithDefault(DateUtils.FORMAT_DATE_COMPLETE, event.getEndTime()));
 
-        welcomeMessage.setText(getText(R.string.welcome_message));
-        Views.setHtml(organiser_description, event.getOrganizerDescription(), true);
-        Views.setHtml(event_description, event.getDescription(), true);
-        venue_details.setText(event.getLocationName());
-        event_timing.setText(date);
+        welcomeMessage.setText(getText(R.string.welcome_message) + " " + event.getName());
```
Comment (rohanagarwal94) [inline android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: This will cause localisation issues in the future. It is better to use `String.format` for this. Please refer this for help - https://stackoverflow.com/a/24098427

**Review by rohanagarwal94 — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java (hunk 3 above)
Comment (arp95) [reply android/app/src/main/java/org/fossasia/openevent/fragments/AboutFragment.java]: umm is the localization necessary for the title? anyways doing it for now.

**Review by rohanagarwal94 — APPROVED** [review]

**Review by Shailesh351 — APPROVED** [review]

**Review by the-dagger — APPROVED** [review]
