### PR TITLE
Memory bug fixes

### LINKED ISSUE #2137: Potential memory leak in many fragments
**Actual Behaviour**

Memory leaks in DayScheduleFragment, FeedFragment, LocationsFragment, ScheduleFragment, SpeakerListFragment, SponsorsFragment, TracksFragment.

Recycler View Instances didn't unregister adapterDataObserver

**Expected Behaviour**

Recycler View should unregister and adapter should be removed

**Would you like to work on the issue?**
yes

### PR DESCRIPTION
**Pull request by simarsingh24**
Fixes #2137

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java [hunk 1]
```diff
@@ -116,7 +116,7 @@ public void handleVisibility() {
     @Override
     public void onDestroyView() {
         super.onDestroyView();
-
+        feedAdapter.setOnImageZoomListener(null);
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java]: Actually feedAdapter has a method called ```removeOnImageZoomListener```. Also it is already called inside the ```onStop```, so you don't need this.

**Review by dr0pdb — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java (hunk 1 above)
Comment (simarsingh24) [reply android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java]: Oh yeah true! Thanks :)

File: android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java [hunk 2]
```diff
@@ -230,6 +230,8 @@ public void closeFilterBar() {
     public void onDestroyView() {
         super.onDestroyView();
         OpenEventApp.getEventBus().unregister(this);
+        viewPager.removeOnPageChangeListener(onPageChangeListener);
+        viewPager.setAdapter(null);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java]: Setting adapter to null doesn't help

**Review by iamareebjamal — CHANGES_REQUESTED** [review]
Nice work, just once change

File: android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java [hunk 3]
```diff
@@ -116,7 +116,6 @@ public void handleVisibility() {
     @Override
     public void onDestroyView() {
         super.onDestroyView();
-
```
Comment (dr0pdb) [inline android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java:120]: @simarsingh24 It's advisable to not do changes that are not related to the issue. Even though this one is very small and hence isn't a problem but it can be a problem if done on a large scale. In case you want to make changes, opening an issue would be the recommended way. Just something to keep in mind. :smile:

**Review by dr0pdb — APPROVED** [review]

**Review by iamareebjamal — APPROVED** [review]

File: android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java (hunk 3 above)
Comment (simarsingh24) [reply android/app/src/main/java/org/fossasia/openevent/fragments/FeedFragment.java:120]: Yeah totally! I will keep that in mind :)
