### PR TITLE
fix #2363: Fix undo button not updating bookmark icon

### LINKED ISSUE #2363: Undo button in SnackBar doesn't update bookmark icon in SpeakerDetailsActivity
**Actual Behaviour**

Clicking undo button in the SnackBar generated after adding a session to bookmarks doesn't update the bookmark icon on that session

**Expected Behaviour**

Clicking the undo button should also change the bookmark icon from bookmarked to not bookmarked

**Steps to reproduce it**

1. Click on any speaker from the Featured Speakers list or go to any speaker's detail activity from the list of speakers
2. Add any session to bookmarks and then click undo in the SnackBar shown.

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by pulakdp**
Fixes #2363 

Changes: Added method onBookmarksChanged() that gets called when a bookmark is added or removed. Refactored code that loads speaker details to avoid code repetition. Created method loadData() for that purpose.

### CODE REVIEW

**Comment by dr0pdb** [comment]
@pulakdp Please atttach a GIF showing that it indeed solves the issue.

**Comment by pulakdp** [comment]
Sure @srv-twry. Here is the gif after the fix

File: android/app/src/main/java/org/fossasia/openevent/core/speaker/SpeakerDetailsActivity.java [hunk 1]
```diff
@@ -286,6 +288,21 @@ private void hideEmptyURLButtons() {
...
+        speakerDetailsViewModel.getSpeaker(speakerName).observe(this, speakerData -> {
+            selectedSpeaker = speakerData;
+            loadSpeakerDetails();
+        });
+    }
+
+    @Subscribe
+    public void onBookmarksChanged(BookmarkChangedEvent bookmarkChangedEvent) {
+        Timber.d("Bookmarks Changed");
+        loadData();
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/speaker/SpeakerDetailsActivity.java]: I think this and many other solutions mask a greater problem with the implementation. We can accept these changes. But write a TODO, that this is a workaround and fix needs to be done in the implementation of RealmLiveData

Also, we are moving away from event bus architecture, so we don't want to add new code using the pattern

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

**Comment by pulakdp** [comment]
@iamareebjamal Added the TODO, have a look

File: android/app/src/main/java/org/fossasia/openevent/core/speaker/SpeakerDetailsActivity.java [hunk 2]
```diff
@@ -286,6 +288,22 @@ private void hideEmptyURLButtons() {
...
+            loadSpeakerDetails();
+        });
+    }
+
+    //TODO: Workaround. Needs fix during implementation of RealmLiveData
+    @Subscribe
+    public void onBookmarksChanged(BookmarkChangedEvent bookmarkChangedEvent) {
+        Timber.d("Bookmarks Changed");
+        loadData();
+    }
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/speaker/SpeakerDetailsActivity.java:304]: This needs to be added in onResume

And the solution should not contain event handling

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/core/speaker/SpeakerDetailsActivity.java (hunk 2 above)
Comment (pulakdp) [reply android/app/src/main/java/org/fossasia/openevent/core/speaker/SpeakerDetailsActivity.java:304]: > This needs to be added in onResume

You mean the TODO?

> And the solution should not contain event handling

How do you suggest I do this @iamareebjamal ? I'm relatively new to the project and I came to the solution after looking at how things were done in TrackSessionsActivity.java. setBookmark() in RealmDataRepository class posts the event so my first thought was to add this method onBookmarksChanged(). If there are other ways to do this, suggest me and I'll try that. Thanks!

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/core/speaker/SpeakerDetailsActivity.java:304]: > You mean the TODO?
Yes

And about the event based method, yes this is how we are doing things currently in the project but we are refactoring code to avoid this and hence we don't want to add new code using this bad practice. The LiveData itself should handle the reactivity and there should be no need of the change event

Comment (pulakdp) [reply android/app/src/main/java/org/fossasia/openevent/core/speaker/SpeakerDetailsActivity.java:304]: Okay, thanks for the clarification @iamareebjamal! For now, just moved the TODO.

**Comment by pulakdp** [comment]
Moved the TODO

File: android/app/src/main/java/org/fossasia/openevent/core/speaker/SpeakerDetailsActivity.java [hunk 3]
```diff
@@ -286,6 +288,22 @@ private void hideEmptyURLButtons() {
...
+
+    @Subscribe
+    public void onBookmarksChanged(BookmarkChangedEvent bookmarkChangedEvent) {
+        Timber.d("Bookmarks Changed");
+        loadData();
+    }
+
+
+    //TODO: Workaround. Needs fix during implementation of RealmLiveData
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/speaker/SpeakerDetailsActivity.java]: Should be at the method call of loadData

**Comment by pulakdp** [comment]
Apologies! Moved TODO inside onResume where loadData is called @iamareebjamal

**Comment by pulakdp** [comment]
@iamareebjamal Kindly review and let me know if any further changes are needed

File: android/app/src/main/java/org/fossasia/openevent/core/speaker/SpeakerDetailsActivity.java (hunk 2 above)
Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/core/speaker/SpeakerDetailsActivity.java:304]: The event bus pattern is still used

Comment (pulakdp) [reply android/app/src/main/java/org/fossasia/openevent/core/speaker/SpeakerDetailsActivity.java:304]: > We can accept these changes. But write a TODO, that this is a workaround and fix needs to be done in the implementation of RealmLiveData

Isn't this why we added a TODO @iamareebjamal? I understand this isn't what you want in future but your earlier instruction was to include a TODO so I did likewise. If a solution with RealmLiveData is expected at the moment then I'll have to learn about LiveData more before I come up with the solution.

**Comment by iamareebjamal** [comment]
@pulakdp The solution still consists of eventbus pattern

**Comment by pulakdp** [comment]
> We can accept these changes. But write a TODO, that this is a workaround and fix needs to be done in the implementation of RealmLiveData

Isn't this why we added a TODO @iamareebjamal? I understand this isn't what you want in future but your earlier instruction was to include a TODO so I did likewise. If a solution with RealmLiveData is expected at the moment then I'll have to learn about LiveData more before I come up with the solution.

**Comment by iamareebjamal** [comment]
The TODO is for the hook in onResume, event bus is deprecated, but I guess we can go ahead with it. Add another above the subscribe event

`TODO: High Priority: Remove event bus pattern`

**Comment by pulakdp** [comment]
@iamareebjamal done.

**Review by iamareebjamal — APPROVED** [review]
