### PR TITLE
fix: app crashes when facebook page id not found using page name

### LINKED ISSUE #2362: Crash: App crashes on reload in live feed activity when no posts is there
**Actual Behaviour**

App crashes on reload in live feed activity when no posts is there.

**Expected Behaviour**

App should not crash on reloading when no posts is there.

**Steps to reproduce it**

1. Generate apk from googleio17 sample provided here : **https://github.com/fossasia/open-event/blob/master/sample/GoogleIO17.zip** 
2. Go to live Feed activity.
3. After Downloading Live Feed pop up close,Try to reload feed by swipe down.

**LogCat for the issue**

03-10 15:29:43.022 15513-15513/org.fossasia.openevent.GoogleIO2017 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: org.fossasia.openevent.GoogleIO2017, PID: 15513
                                                                                     java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
                                                                                         at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
                                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                                                      Caused by: **java.lang.RuntimeException: LiveData does not handle errors. Errors from publishers should be handled upstream and propagated as state**
                                                                                         at android.arch.lifecycle.LiveDataReactiveStreams$PublisherLiveData$LiveDataSubscriber$1.run(LiveDataReactiveStreams.java:262)
                                                                                         at android.arch.core.executor.TaskExecutor.executeOnMainThread(TaskExecutor.java:54)
                                                                                         at android.arch.lifecycle.LiveDataReactiveStreams$PublisherLiveData$LiveDataSubscriber.onError(LiveDataReactiveStreams.java:258)
                                                                                         at io.reactivex.internal.util.HalfSerializer.onError(HalfSerializer.java:70)
                                                                                         at io.reactivex.internal.subscribers.StrictSubscriber.onError(StrictSubscriber.java:103)
                                                                                         at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.checkTerminated(FlowableOnBackpressureBuffer.java:235)
                                                                                         at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.drain(FlowableOnBackpressureBuffer.java:166)
                                                                                         at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onError(FlowableOnBackpressureBuffer.java:123)
                                                                                         at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onError(FlowableFromObservable.java:47)
                                                                                         at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
                                                                                         at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
                                                                                         at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                                                         at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                                         at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                         at android.os.Looper.loop(Looper.java:154) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6692) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
                                                                                      Caused by: **retrofit2.adapter.rxjava2.HttpException: HTTP 404** 
                                                                                         at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
                                                                                         at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
                                                                                         at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:43)
                                                                                         at io.reactivex.Observable.subscribe(Observable.java:10903)
                                                                                         at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
                                                                                         at io.reactivex.Observable.subscribe(Observable.java:10903)
                                                                                         at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                                                                                         at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                                         at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                                         at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                         at java.lang.Thread.run(Thread.java:762)

**Screenshots of the issue**

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by ParthivMangukiya**
Fixes #2362 
Changes: Changed facebook page id publisher to return invalid id when unable to find page id from page name.

Screenshot of the changes:

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/core/feed/facebook/FacebookFeedFragmentViewModel.java [hunk 1]
```diff
@@ -36,6 +36,10 @@ public FacebookFeedFragmentViewModel() {
         if (fbPageId == null) {
             Publisher<FacebookPageId> publisher = FacebookApi.getFacebookGraphAPI().getPageId(SharedPreferencesUtil.getString(ConstantStrings.FACEBOOK_PAGE_NAME, null),
                     fbAccessToken)
+                    .onErrorReturn(throwable -> {
+                        Timber.e(throwable);
+                        return new FacebookPageId(null, FacebookPageId.INVALID);
+                    })
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/feed/facebook/FacebookFeedFragmentViewModel.java]: It's not necessary that each error is about facebook page ID. Detect the specific error and throw only if matched

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/core/feed/facebook/FacebookFeedFragmentViewModel.java (hunk 1 above)
Comment (ParthivMangukiya) [reply android/app/src/main/java/org/fossasia/openevent/core/feed/facebook/FacebookFeedFragmentViewModel.java]: @iamareebjamal If the error is not related to 404 then what should we return? because UI should be informed that error has occurred and can stop swipe refresh layout.

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/core/feed/facebook/FacebookFeedFragmentViewModel.java]: Let the error propagate as usual

Comment (ParthivMangukiya) [reply android/app/src/main/java/org/fossasia/openevent/core/feed/facebook/FacebookFeedFragmentViewModel.java]: because we are wrapping publisher in live data we can not propagate error (that's the reason for crashing), we need to handle it there only. 
we can wrap the facebookPageId in Resource live data that can contain data, status, error message as used in Google's sample on Android Architecture components https://github.com/googlesamples/android-architecture-components/blob/master/GithubBrowserSample/app/src/main/java/com/android/example/github/vo/Resource.java.

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/core/feed/facebook/FacebookFeedFragmentViewModel.java]: Use a wrapper

File: android/app/src/main/java/org/fossasia/openevent/core/feed/facebook/FacebookFeedFragmentViewModel.java [hunk 2]
```diff
@@ -7,35 +7,32 @@
...
     }
 
-    public LiveData<FacebookPageId> updateFBPageID(String fbAccessToken, String fbPageId) {
+    public LiveData<Resource<FacebookPageId>> updateFBPageID(String fbAccessToken, String fbPageId) {
         if (fbPageId == null) {
-            Publisher<FacebookPageId> publisher = FacebookApi.getFacebookGraphAPI().getPageId(SharedPreferencesUtil.getString(ConstantStrings.FACEBOOK_PAGE_NAME, null),
+            Publisher<Resource<FacebookPageId>> publisher = FacebookApi.getFacebookGraphAPI().getPageId(SharedPreferencesUtil.getString(ConstantStrings.FACEBOOK_PAGE_NAME, null),
                     fbAccessToken)
+                    .map(Resource.Companion::success)
+                    .onErrorReturn(throwable -> Resource.Companion.error(throwable.getMessage(), null))
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/feed/facebook/FacebookFeedFragmentViewModel.java]: Use JvmStatic and remove Companion

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/core/feed/facebook/FacebookFeedFragmentViewModel.java]: Log the error as well because we won't be able to see stack trace otherwise

File: android/app/src/main/java/org/fossasia/openevent/core/feed/facebook/FacebookFeedFragmentViewModel.java [hunk 3]
```diff
@@ -44,22 +41,18 @@ public FacebookFeedFragmentViewModel() {
...
 
-    public LiveData<PostsResponse> getPosts(String fields, String fbAccessToken, String fbPageId) {
-        compositeDisposable.add(FacebookApi.getFacebookGraphAPI()
+    public LiveData<Resource<Feed>> getPosts(String fields, String fbAccessToken, String fbPageId) {
+        Publisher<Resource<Feed>> publisher = FacebookApi.getFacebookGraphAPI()
                 .getPosts(fbPageId,
                         fields,
                         fbAccessToken)
+                .map(Resource.Companion::success)
+                .onErrorReturn(throwable -> Resource.Companion.error(throwable.getMessage(), null))
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/feed/facebook/FacebookFeedFragmentViewModel.java]: Here as well

File: android/app/src/main/java/org/fossasia/openevent/core/feed/twitter/TwitterFeedFragmentViewModel.java [hunk 4]
```diff
@@ -1,42 +1,34 @@
...
-        compositeDisposable = new CompositeDisposable();
         feedLiveData = new MutableLiveData<>();
     }
 
-    public LiveData<PostsResponse> getPosts(String query, int count, String source) {
-        compositeDisposable.add(TwitterApi.getLoklakAPI().getTwitterFeed(query, count, source)
+    public LiveData<Resource<TwitterFeed>> getPosts(String query, int count, String source) {
+        Publisher<Resource<TwitterFeed>> publisher = TwitterApi.getLoklakAPI().getTwitterFeed(query, count, source)
+                .map(Resource.Companion::success)
+                .onErrorReturn(throwable -> Resource.Companion.error(throwable.getMessage(), null))
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/feed/twitter/TwitterFeedFragmentViewModel.java]: Here as well

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/core/feed/twitter/TwitterFeedFragmentViewModel.java [hunk 5]
```diff
@@ -1,42 +1,38 @@
...
+                .onErrorReturn(throwable -> {
+                    Timber.e(throwable);
+                    return Resource.error(throwable.getMessage(), null);
+                })
                 .subscribeOn(Schedulers.io())
                 .observeOn(AndroidSchedulers.mainThread())
-                .subscribe(feed -> feedLiveData.setValue(new PostsResponse(VALID, feed))
-                    , throwable -> feedLiveData.setValue(new PostsResponse(INVALID, null))));
+                .toFlowable(BackpressureStrategy.BUFFER);
+        feedLiveData = LiveDataReactiveStreams.fromPublisher(publisher);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/feed/twitter/TwitterFeedFragmentViewModel.java]: This should only be initialized once, and returned directly later on

Comment (iamareebjamal) [reply android/app/src/main/java/org/fossasia/openevent/core/feed/twitter/TwitterFeedFragmentViewModel.java]: Similarly with other entries as well

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

**Comment by ParthivMangukiya** [comment]
@iamareebjamal there is two refreshing layout in feed fragment. one is progress bar dialog box on onCreate and another is swipe refresh layout. We could only use swiper refresh layout. as there is no need for two layouts Should I remove progress dialog box?

**Comment by iamareebjamal** [comment]
Yes

**Comment by iamareebjamal** [comment]
Nice work. Please add gifs to show how it works with/without internet

**Review by iamareebjamal — APPROVED** [review]
