### PR TITLE
fix : Set correct alarm time

### LINKED ISSUE #1919: Alarm for event set at wrong time
**Actual Behaviour**

Alarm set 10 ***hours*** before the event

**Expected Behaviour**

Alarm should set 10 ***min*** before the event

**Screenshots of the issue**

screenshot

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by manav-mj**
Fixes #1919 

Changes: Replace minusHours with minusMinutes

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/utils/NotificationUtil.java [hunk 1]
```diff
@@ -35,7 +35,7 @@ public static Completable createNotification(Session session, Context context) {
             } else if (pref_result.equals(12)) {
                 zonedDateTime.minusHours(12);
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/utils/NotificationUtil.java:36]: Shouldn't this also be changed @manav-mj ?

Comment (manav-mj) [reply android/app/src/main/java/org/fossasia/openevent/utils/NotificationUtil.java:36]: We have the option for
1. 10 min
2. 1 hour
3. 12 hour

**Review by iamareebjamal — APPROVED** [review]

**Review by iamareebjamal — CHANGES_REQUESTED** [review]
Build is failing. Please fix it

**Review by scandindian — APPROVED** [review]

**Review by iamareebjamal — APPROVED** [review]
