### PR TITLE
fix: unnecessary elements removed from speaker details

### LINKED ISSUE #2219: Unnecessary elements showing up while sharing speaker details
**Actual Behaviour**

Unnecessary elements are showing up while sharing the speaker details.

**Expected Behaviour**

Only the relevant details should show up like the name of the session and session details

**Steps to reproduce it**

Open speaker details activity and select share from options menu

**Screenshots of the issue**

screenshot_20180126-150845

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by nikit19**
Fixes #2219 

Changes: unnecessary elements removed from speaker details

Screenshots for the change: 
screenshot_20180126-192917

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java [hunk 1]
```diff
@@ -319,6 +320,16 @@ private static int getDarkColor(int color) {
...
+                StringBuilder sessionsBuilder = new StringBuilder();
+                boolean firstSession = true;
+                for (Session session : sessions) {
+                    if (!firstSession) {
+                        sessionsBuilder.append(", ");
+                    }
+                    sessionsBuilder.append(session.getTitle() + session.getShortAbstract());
+                    firstSession = false;
+                }
+
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java]: Move this to a static utility method to share this

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java (hunk 1 above)
Comment (nikit19) [reply android/app/src/main/java/org/fossasia/openevent/activities/SpeakerDetailsActivity.java]: Done. Please review

**Review by iamareebjamal — APPROVED** [review]
