### PR TITLE
Fix #1986-Provide option to download data in the app.

### LINKED ISSUE #1986: No option to download data once user says no
**Actual Behaviour**

If the user selects no for downloading data at start up, there is no option to download it again.
Only option is to restart the app.

**Expected Behaviour**

There should be an option to download data in the overflow menu.

**Steps to reproduce it**

Open the app and select no for downloading data.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by mayank8318**
Fixes #1986 

Changes: Add a menu item for downloading data

Screenshots for the change: 
23419125_1867275683301237_8488570078164418560_n

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java [hunk 1]
```diff
@@ -417,7 +417,7 @@ private void downloadPageId() {
         }
     }
 
-    private void setupConnection() {
+    public void setupConnection() {
```
Comment (scandindian) [inline android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: This works but it's not a good practice. :-/

**Review by scandindian — APPROVED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java (hunk 1 above)
Comment (mayank8318) [reply android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: Should I move it to an utils class and make it a static method? But it will have to be public still.

Comment (scandindian) [reply android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: Yes that'd be better .

Comment (mayank8318) [reply android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: @heysadboy I tried doing that but there is a long list of chained calls to different methods all of which are private to MainAcitivity and non-static. Some of them also affect the UI. I am facing problems transferring all this to a Utils class. How should I go about it?
Thanks :)

Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: How about renaming this method to reflect that this means dowloading data? 😄

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java (hunk 1 above)
Comment (mayank8318) [reply android/app/src/main/java/org/fossasia/openevent/activities/MainActivity.java]: Yes that would be best. On it.

**Comment by mayank8318** [comment]
@iamareebjamal Changed the name to ` downloadData() `

**Review by iamareebjamal — APPROVED** [review]
