### PR TITLE
fix: Using AuthUtils in SignUpActivity and removed usage of Pair in ViewModels

### LINKED ISSUE #2200: Refactor the SignUpActivityViewModel and remove all usage of Pair from ViewModels
**Actual Behaviour**

Currently the Pair class is being used inside the SignUpActivityViewModel. Also it has code used by both itself and LoginActivity.

**Expected Behaviour**

Pair shouldn't be used as it is android specific. Also remove it's usage in other ViewModels.
Delete common methods and use the common code present in AuthUtils.

**Would you like to work on the issue?**

Yes

Can only be done after #2197 is merged.

### PR DESCRIPTION
**Pull request by dr0pdb**
Fixes #2200 

Changes: Using AuthUtils in SignUpActivity. Removed the usage of Pair class in ViewModels.

Screenshots for the change: NA

@iamareebjamal Please review.

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java [hunk 1]
```diff
@@ -100,7 +100,7 @@ private void setupViewPager(final ViewPager viewPager) {
 
         scheduleFragmentViewModel.getEventDateString().observe(this, datePair -> {
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/fragments/ScheduleFragment.java]: Rename datePair

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

**Comment by dr0pdb** [comment]
Renamed datePair to dateStrings.
@iamareebjamal Please review.

**Review by iamareebjamal — APPROVED** [review]
