### PR TITLE
fix : Open LiveFeed links with custom intent dialog (#1912)

### LINKED ISSUE #1912: Opening Live Feed links within the app using customTab
**Actual Behaviour**
The links (like the facebook link) in the Live Feed list-items open in chrome (uses Implicit Intent).

**Expected Behaviour**
The links should open within the app like the social media links on the homepage (should use CustomTabsIntent).

**Steps to reproduce it**
1. Go to Live Feed from navigation drawer.
2. Click the link in the item cards.

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by manav-mj**
Fixes #1912 

Changes: Opens live feed link URL in custom tab

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/adapters/FeedAdapter.java [hunk 1]
```diff
@@ -120,7 +119,9 @@ public void onBindViewHolder(RecyclerViewHolder holder, int position) {
                     + feedItem.getLink() + "</a> "));
 
             // Making url clickable
-            holder.url.setMovementMethod(LinkMovementMethod.getInstance());
+            holder.url.setOnClickListener(v -> {
+                Utils.setUpCustomTab(context, feedItem.getLink());
+            });
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/adapters/FeedAdapter.java]: Please rename lambda variable to `view`

And in case of one line functions, it's ok to remove the curly braces for brevity :smile:

**Review by iamareebjamal — CHANGES_REQUESTED** [review]

**Comment by manav-mj** [comment]
@iamareebjamal  Pls. review again

**Review by iamareebjamal — APPROVED** [review]

**Review by scandindian — APPROVED** [review]
