### PR TITLE
fix : Replace live feed image placeholder

### LINKED ISSUE #1764: Set appropriate placeholder for the live feed
**Actual Behaviour**

The placeholder currently set looks absurd and out of context.

**Expected Behaviour**

The placeholder should look apt for the task.

**Screenshots of the issue**

screenshot_2017-07-02-23-09-52-853_org fossasia openevent

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

[milestone 9](https://github.com/fossasia/open-event-android/milestone/32)

### PR DESCRIPTION
**Pull request by rohanagarwal94**
Fixes #1764 

Screenshots for the change: 
Screenshots in the issue.

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
@iamareebjamal @arp95 @Shailesh351 @shreyasnbhat please review.

File: android/app/src/main/java/org/fossasia/openevent/adapters/FeedAdapter.java [hunk 1]
```diff
@@ -5,6 +5,8 @@
 import android.net.Uri;
 import android.support.design.widget.Snackbar;
 import android.support.graphics.drawable.VectorDrawableCompat;
+import android.support.v4.content.ContextCompat;
+import android.support.v4.graphics.drawable.DrawableCompat;
```
Comment (shreyasnbhat) [inline android/app/src/main/java/org/fossasia/openevent/adapters/FeedAdapter.java]: To avoid such errors do a Code Inspection before each PR. You could remove such errors easily.

**Comment by Shailesh351** [comment]
When app is offline it will show big place holders. IMO it is not good. If image is not loaded we can set visibility to GONE

**Comment by iamareebjamal** [comment]
This will cause jumps in the UI while the images are being loaded confusing the user and throwing UI off place

**Comment by rohanagarwal94** [comment]
@iamareebjamal @Shailesh351 what else should be done then. Since the height of the image is not known till the image is loaded from the uri, it is not possible to decide on the height of the placeholder as well.

**Comment by Shailesh351** [comment]
Will resizing and centring image work? Like implemented in Sponsors adapter.

**Comment by iamareebjamal** [comment]
@Shailesh351, still the placeholder is shown there too. I think showing placeholder is appropriate. Jumping UI once image loads is bad UX

**Comment by rohanagarwal94** [comment]
I think not since the image height is not constant. Even the sponsors make the UI jump.

**Comment by iamareebjamal** [comment]
That's true. Even Sponsors page should have placeholder images, but this is another issue

**Comment by arp95** [comment]
yes you are right. sponsors should also have a placeholder.

**Comment by rohanagarwal94** [comment]
So is there anything that needs to be changed in this PR?

**Review by arp95 — APPROVED** [review]
LGTM.

**Review by iamareebjamal — APPROVED** [review]

**Comment by arp95** [comment]
@rohanagarwal94 
shoudl i open an issue regarding sponsors placeholders or you would do it?

**Review by Shailesh351 — APPROVED** [review]

**Comment by shreyasnbhat** [comment]
@arp95 I'll do this.

**Comment by rohanagarwal94** [comment]
@arp95 Please open it.

**Review by shreyasnbhat — APPROVED** [review]

**Comment by shreyasnbhat** [comment]
@rohanagarwal94 I have created the issue.

**Review by mahikaw — APPROVED** [review]
