### PR TITLE
Fix #2395 - Let the user select his sharing medium everytime

### LINKED ISSUE #2395: Let the user choose his sharing medium everytime
**Actual Behaviour**

Presently, a default sharing medium is selected(according to the user's preference).

**Expected Behaviour**

We should let the user choose the sharing medium everytime he wants to share anything.
This involves using `Intent.createChooser()`

**Steps to reproduce it**

Share anything from the app.
Now try to share again

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by mayank8318**
Fixes #2395 

Changes: Replace `startActivity()` with `startActivity(Intent.createChooser())` in shareApp()

### CODE REVIEW

File: android/app/src/main/java/org/fossasia/openevent/core/main/MainActivity.java [hunk 1]
```diff
@@ -493,7 +493,7 @@ private void shareApplication() {
             shareIntent.setType("text/plain");
             shareIntent.putExtra(Intent.EXTRA_TEXT, String.format(getString(R.string.whatsapp_promo_msg_template),
                     String.format(getString(R.string.app_share_url),getPackageName())));
-            startActivity(shareIntent);
+            startActivity(Intent.createChooser(shareIntent, "Share via"));
```
Comment (iamareebjamal) [inline android/app/src/main/java/org/fossasia/openevent/core/main/MainActivity.java]: Use strings.xml

**Comment by mayank8318** [comment]
@iamareebjamal Made the changes, sorry for the lazy mistake :(

**Review by iamareebjamal — DISMISSED** [review]

**Review by iamareebjamal — DISMISSED** [review]

**Review by iamareebjamal — APPROVED** [review]
